const CACHE="oneshop-v5.9.18-photo-recovery-01";
const CORE=["./","index.html","styles.css","app.js","app-core-v5.6.3.js","one-shop-hotfix-v581.js","one-shop-fast-boot-v582.js","one-shop-performance-v595.js","one-shop-lazy-modules-v596.js","one-shop-drive-sync-v599.js","one-shop-photo-recovery-v600.js","one-shop-orientation-v583.js","one-shop-evidence-v584.js","one-shop-evidence-v585.js","one-shop-camera-parity-v586.js","one-shop-tramos-v587.js","one-shop-tramo-media-v588.js","one-shop-evidence-order-v590.js","one-shop-evidence-fast-v591.js","one-shop-location-guard-v594.js","one-shop-selection-bar-v592.js","one-shop-evidence-progress-v598.js","one-shop-dashboard-packages-v593.js","one-shot-catalog-sync-v620.js","one-shot-party-fallback-v597.js","one-shop-dashboard-packages-v640.js","version.json","manifest.json","oneshot-erm-data.js","one-shop-stable-runtime.js","one-shop-field-quality-v578.js","one-shop-excel-thumb-v579.js","one-shop-storage-lite-v578.js","one-shop-field-tools-v571.js","one-field-report-standard.js","oneshot-logo.svg","oneshot-mark.png","oneshot-mark-transparent.png","icon-192.png","icon-512.png"];
const OPTIONAL=["one-migrate-to-one-shot2.js","one-dropbox-legacy-sync.js","one-dropbox-write-diagnostic.js","one-dropbox-same-origin-proxy.js","one-phase1-batch-migration.js","one-dropbox-legacy-sync.css"];
function slimShell(html){return String(html||"").replace(/\s*<link[^>]+leaflet@1\.9\.4\/dist\/leaflet\.css[^>]*>/ig,"").replace(/\s*<script[^>]+exceljs@4\.4\.0\/dist\/exceljs\.min\.js[^>]*><\/script>/ig,"").replace(/\s*<script[^>]+leaflet@1\.9\.4\/dist\/leaflet\.js[^>]*><\/script>/ig,"")}
async function timedFetch(request,options={},ms=4500){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(request,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
async function shell(request){const c=await caches.open(CACHE);let r;try{r=await timedFetch(request,{cache:"no-store"},4500)}catch(_){r=await c.match("index.html")||await c.match("./")}if(!r)throw new Error("ONE SHOP no disponible");return new Response(slimShell(await r.text()),{status:200,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}})}
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE).catch(()=>{})))});
self.addEventListener("activate",e=>{e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE&&(k.startsWith("oneshot-")||k.startsWith("oneshop-")).map(k=>caches.delete(k)));await self.clients.claim()})())});
self.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting();if(e.data?.type==="CLEAR_CACHES")e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith("oneshot-")||k.startsWith("oneshop-")).map(k=>caches.delete(k)))))});
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url);if(u.origin!==location.origin)return;
  if(u.pathname==="/control"||u.pathname.startsWith("/control/"))return;
  const isShell=e.request.mode==="navigate"||u.pathname==="/"||u.pathname.endsWith("/index.html");if(isShell){e.respondWith(shell(e.request));return}
  const isVersion=u.pathname.endsWith("version.json");
  if(isVersion){e.respondWith(fetch(e.request,{cache:"no-store"}).catch(()=>caches.match(e.request)));return}
  e.respondWith((async()=>{const c=await caches.open(CACHE),hit=await c.match(e.request);if(hit){timedFetch(e.request,{cache:"no-store"},4500).then(r=>{if(r.ok)c.put(e.request,r.clone())}).catch(()=>{});return hit}try{const r=await timedFetch(e.request,{cache:"reload"},6500);if(r.ok)await c.put(e.request,r.clone());return r}catch(err){const fallback=await caches.match(e.request);if(fallback)return fallback;throw err}})())})