'use strict';
(() => {
const BUILD='control-v0.2.1-593';
const SUPA_URL='https://jdupbwkbitkcwhnsslkk.supabase.co',SUPA_KEY='sb_publishable_j8mj7pLl_Bt713wzmG0oKg_lKfphiO3';
const S={all:[],visible:[],selected:[],current:null,markers:new Map(),area:null,source:'',map:null,drawn:null,markerLayer:null,db:null,renderSeq:0,filterSig:'',booted:false};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v??'').trim(),yieldUI=()=>new Promise(r=>setTimeout(r,0));
function notice(text,tone='info'){const n=$('bootNotice');if(!n)return;n.textContent=text;n.dataset.tone=tone;n.hidden=!text;}
function status(text,color=''){const b=$('syncBadge');if(!b)return;b.textContent=text;b.style.color=color||'';}
function statusOf(r){return norm(r.review_status||r.status||r.type)==='PENDIENTE'?'PENDIENTE':norm(r.review_status||'REVISADO')||'REVISADO'}
function color(r){return statusOf(r)==='PENDIENTE'?'#ef4444':statusOf(r)==='ACTUALIZAR'?'#f59e0b':statusOf(r)==='RETIRADO'?'#64748b':'#16a34a'}
function validPoint(r){return Number.isFinite(+r.latitude)&&Number.isFinite(+r.longitude)&&Math.abs(+r.latitude)<=90&&Math.abs(+r.longitude)<=180&&(+r.latitude!==0||+r.longitude!==0)}
function initMap(){
 if(!window.L)throw new Error('Leaflet no cargó. Recarga la página.');
 const host=$('map');if(host)host.innerHTML='';
 S.map=L.map('map',{preferCanvas:true,zoomControl:true}).setView([-9.2,-75.0],5);
 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap',updateWhenIdle:true,keepBuffer:2}).addTo(S.map);
 S.drawn=new L.FeatureGroup().addTo(S.map);S.markerLayer=L.layerGroup().addTo(S.map);
 if(L.Control?.Draw){S.map.addControl(new L.Control.Draw({draw:{polyline:false,rectangle:false,circle:false,circlemarker:false,marker:false,polygon:{allowIntersection:false,showArea:true}},edit:{featureGroup:S.drawn,remove:true}}));
  S.map.on(L.Draw.Event.CREATED,e=>{S.drawn.clearLayers();S.drawn.addLayer(e.layer);S.area=e.layer.toGeoJSON().geometry.coordinates[0].map(([x,y])=>[y,x]);selectArea()});
  S.map.on(L.Draw.Event.EDITED,e=>{const l=e.layers.getLayers()[0];if(l){S.area=l.toGeoJSON().geometry.coordinates[0].map(([x,y])=>[y,x]);selectArea()}});
  S.map.on(L.Draw.Event.DELETED,clearArea);
 }
}
function dbClient(){if(S.db)return S.db;if(window.supabase?.createClient)S.db=window.supabase.createClient(SUPA_URL,SUPA_KEY,{auth:{persistSession:false,autoRefreshToken:false}});return S.db}
async function loadCentral(){
 const db=dbClient();if(!db){status('● Local');$('importMsg').textContent='Modo local · Supabase no cargó';return}
 status('● Conectando…','#facc15');$('importMsg').textContent='Leyendo base central…';
 try{
  const rows=[];const page=1000;for(let from=0;from<50000;from+=page){const {data,error}=await db.from('control_evidences').select('*').order('capture_date',{ascending:false}).range(from,from+page-1);if(error)throw error;rows.push(...(data||[]));notice(`Cargando base central… ${rows.length} evidencias`);await yieldUI();if(!data||data.length<page)break}
  S.all=rows;status('● Central conectado','#8ff0b5');$('importMsg').textContent=`Base central · ${S.all.length} evidencias`;notice('');render({fit:true});
 }catch(e){console.warn(e);status('● Modo local');$('importMsg').textContent='Base central no disponible · puedes trabajar con Excel local';notice('El panel sigue operativo en modo local.','warn')}
}
function mapRow(x,i,name){return {code:norm(x['CÓDIGO']||x.CODIGO||x.ID||`ROW-${i+1}`),verifier:norm(x['VERIFICADOR']),capture_date:norm(x['FECHA']),capture_time:norm(x['HORA']),latitude:+x['LATITUD'],longitude:+x['LONGITUD'],gps_accuracy:+x['GPS ±m']||null,altitude:+x['ALTITUD']||null,ubigeo:norm(x['UBIGEO']),region:norm(x['REGIÓN']),province:norm(x['PROVINCIA']),district:norm(x['DISTRITO']),address:norm(x['DIRECCIÓN CAPTURA']),type:norm(x['TIPO']||'PENDIENTE'),party:norm(x['PARTIDO']),provider:norm(x['EMPRESA / PROVEEDOR']),process:norm(x['PROCESO']),orientation:norm(x['ORIENTACIÓN CAPTURA']),pipeline:norm(x['PIPELINE']),sha_original:norm(x['SHA-256 ORIGINAL']),sha_marked:norm(x['SHA-256 MARCADA']),review_status:norm(x['TIPO'])==='PENDIENTE'?'PENDIENTE':'REVISADO',source_file:name,notes:''}}
function parseExcelMain(buf,name){const wb=XLSX.read(buf,{type:'array',cellStyles:false,cellFormula:false,cellHTML:false}),ws=wb.Sheets['DATOS_TECNICOS']||wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});return raw.map((x,i)=>mapRow(x,i,name)).filter(validPoint)}
function parseExcelWorker(buf,name){return new Promise((resolve,reject)=>{
 if(!window.Worker){try{return resolve(parseExcelMain(buf,name))}catch(e){return reject(e)}}
 const code=`importScripts('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');\nself.onmessage=e=>{try{const b=e.data.buf,n=e.data.name;const wb=XLSX.read(b,{type:'array',cellStyles:false,cellFormula:false,cellHTML:false}),ws=wb.Sheets['DATOS_TECNICOS']||wb.Sheets[wb.SheetNames[0]],a=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false}),s=v=>String(v??'').trim();const rows=a.map((x,i)=>({code:s(x['CÓDIGO']||x.CODIGO||x.ID||('ROW-'+(i+1))),verifier:s(x['VERIFICADOR']),capture_date:s(x['FECHA']),capture_time:s(x['HORA']),latitude:+x['LATITUD'],longitude:+x['LONGITUD'],gps_accuracy:+x['GPS ±m']||null,altitude:+x['ALTITUD']||null,ubigeo:s(x['UBIGEO']),region:s(x['REGIÓN']),province:s(x['PROVINCIA']),district:s(x['DISTRITO']),address:s(x['DIRECCIÓN CAPTURA']),type:s(x['TIPO']||'PENDIENTE'),party:s(x['PARTIDO']),provider:s(x['EMPRESA / PROVEEDOR']),process:s(x['PROCESO']),orientation:s(x['ORIENTACIÓN CAPTURA']),pipeline:s(x['PIPELINE']),sha_original:s(x['SHA-256 ORIGINAL']),sha_marked:s(x['SHA-256 MARCADA']),review_status:s(x['TIPO'])==='PENDIENTE'?'PENDIENTE':'REVISADO',source_file:n,notes:''})).filter(r=>Number.isFinite(r.latitude)&&Number.isFinite(r.longitude)&&Math.abs(r.latitude)<=90&&Math.abs(r.longitude)<=180&&(r.latitude!==0||r.longitude!==0));postMessage({ok:true,rows})}catch(err){postMessage({ok:false,error:err.message})}}`;
 const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'})),w=new Worker(url),timer=setTimeout(()=>{w.terminate();URL.revokeObjectURL(url);try{resolve(parseExcelMain(buf,name))}catch(e){reject(e)}},20000);
 w.onmessage=e=>{clearTimeout(timer);w.terminate();URL.revokeObjectURL(url);if(e.data?.ok)resolve(e.data.rows);else reject(new Error(e.data?.error||'Error leyendo Excel'))};w.onerror=()=>{clearTimeout(timer);w.terminate();URL.revokeObjectURL(url);try{resolve(parseExcelMain(buf,name))}catch(e){reject(e)}};w.postMessage({buf,name},[buf]);
})}
async function uploadRows(rows,name){const db=dbClient();if(!db)return false;const chunk=400;for(let i=0;i<rows.length;i+=chunk){notice(`Consolidando ${Math.min(i+chunk,rows.length)} de ${rows.length}…`);const payload=rows.slice(i,i+chunk).map(r=>({...r,updated_at:new Date().toISOString()}));const {error}=await db.from('control_evidences').upsert(payload,{onConflict:'code'});if(error)throw error;await yieldUI()}await db.from('control_imports').insert({file_name:name,row_count:rows.length});return true}
function unique(field){return [...new Set(S.all.map(r=>norm(r[field])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function refreshFilterOptions(){const sig=[S.all.length,...['process','region','district','type','party'].map(f=>unique(f).join('|'))].join('§');if(sig===S.filterSig)return;S.filterSig=sig;[['fProcess','process','Proceso · Todos'],['fRegion','region','Región · Todas'],['fDistrict','district','Distrito · Todos'],['fType','type','Tipo · Todos'],['fParty','party','Partido · Todos']].forEach(([id,field,label])=>{const el=$(id),cur=el.value;el.innerHTML=`<option value="">${label}</option>`+unique(field).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');el.value=cur})}
function filtered(){const get=id=>norm($(id).value),q=get('fSearch').toLowerCase();return S.all.filter(r=>(!get('fProcess')||r.process===get('fProcess'))&&(!get('fRegion')||r.region===get('fRegion'))&&(!get('fDistrict')||r.district===get('fDistrict'))&&(!get('fType')||r.type===get('fType'))&&(!get('fParty')||r.party===get('fParty'))&&(!get('fStatus')||statusOf(r)===get('fStatus'))&&(!q||[r.code,r.address,r.party,r.district,r.type].join(' ').toLowerCase().includes(q)))}
function render(opts={}){const seq=++S.renderSeq;refreshFilterOptions();S.visible=filtered();$('kTotal').textContent=S.all.length;$('kPending').textContent=S.all.filter(r=>statusOf(r)==='PENDIENTE').length;$('kDistricts').textContent=new Set(S.all.map(r=>r.district).filter(Boolean)).size;$('sideCount').textContent=`${S.visible.length} visibles`;paintRows();paintMap(seq,!!opts.fit)}
async function paintMap(seq,fit){if(!S.map||!S.markerLayer)return;S.markerLayer.clearLayers();S.markers.clear();const pts=[];const list=S.visible.slice();const renderer=L.canvas({padding:.5});for(let i=0;i<list.length;i+=250){if(seq!==S.renderSeq)return;for(const r of list.slice(i,i+250)){if(!validPoint(r))continue;const m=L.circleMarker([+r.latitude,+r.longitude],{renderer,radius:7,color:'#fff',weight:2,fillColor:color(r),fillOpacity:.95}).bindPopup(`<div class="pop"><b>${esc(r.code)}</b><small>${esc(r.type)} · ${esc(r.party||'Sin partido')}</small><small>${esc(r.address)}</small><small>${esc(statusOf(r))}</small></div>`);m.on('click',()=>openEdit(r.code));S.markerLayer.addLayer(m);S.markers.set(r.code,m);pts.push([+r.latitude,+r.longitude])}await new Promise(requestAnimationFrame)}if(fit&&pts.length)S.map.fitBounds(pts,{padding:[20,20],maxZoom:15})}
function paintRows(){const h=S.visible.slice(0,500).map(r=>`<div class="row ${S.current?.code===r.code?'on':''}" data-code="${esc(r.code)}"><b>${esc(r.code)} · ${esc(r.type)}</b><span>${esc(r.party||'Sin partido')} · ${esc(r.district||'Distrito pendiente')}</span><span>${esc(r.address)}</span></div>`).join('');$('rows').innerHTML=h||'<div class="empty">Sin resultados.</div>'}
function openEdit(code){const r=S.all.find(x=>x.code===code);if(!r)return;S.current=r;$('editorEmpty').classList.add('hidden');$('editForm').classList.remove('hidden');$('eCode').textContent=r.code;$('eType').value=r.type||'';$('eParty').value=r.party||'';$('eDistrict').value=r.district||'';$('eStatus').value=statusOf(r);$('eNotes').value=r.notes||'';paintRows();S.markers.get(code)?.openPopup()}
async function saveCurrent(){if(!S.current)return;Object.assign(S.current,{type:norm($('eType').value),party:norm($('eParty').value),district:norm($('eDistrict').value),review_status:norm($('eStatus').value),notes:norm($('eNotes').value),updated_at:new Date().toISOString()});try{const db=dbClient();if(S.current.id&&db)await db.from('control_evidences').update({type:S.current.type,party:S.current.party,district:S.current.district,review_status:S.current.review_status,notes:S.current.notes,updated_at:S.current.updated_at}).eq('id',S.current.id)}catch(e){console.warn(e)}const i=S.visible.findIndex(x=>x.code===S.current.code);render();if(i>=0&&S.visible[i+1])openEdit(S.visible[i+1].code)}
function pip(p,poly){let x=p[1],y=p[0],inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const xi=poly[i][1],yi=poly[i][0],xj=poly[j][1],yj=poly[j][0],hit=((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi||1e-12)+xi);if(hit)inside=!inside}return inside}
function selectArea(){if(!S.area)return;S.selected=S.visible.filter(r=>pip([+r.latitude,+r.longitude],S.area));$('kSelected').textContent=S.selected.length;$('missionBtn').disabled=!S.selected.length;for(const r of S.selected)S.markers.get(r.code)?.setStyle({radius:10,weight:4});$('importMsg').textContent=`Perímetro: ${S.selected.length} evidencias existentes. Exporta la misión para trabajo de campo.`}
function clearArea(){S.area=null;S.selected=[];S.drawn?.clearLayers();$('kSelected').textContent='0';$('missionBtn').disabled=true;render()}
function exportMission(){if(!S.selected.length||!window.XLSX)return;const rows=S.selected.map(r=>({'CÓDIGO':r.code,'FECHA':r.capture_date,'HORA':r.capture_time,'LATITUD':r.latitude,'LONGITUD':r.longitude,'GPS ±m':r.gps_accuracy,'REGIÓN':r.region,'PROVINCIA':r.province,'DISTRITO':r.district,'DIRECCIÓN CAPTURA':r.address,'TIPO':r.type,'PARTIDO':r.party,'PROCESO':r.process,'ESTADO MISIÓN':'REVISAR / ACTUALIZAR','OBSERVACIÓN CAMPO':''})),ws=XLSX.utils.json_to_sheet(rows),cfg=XLSX.utils.aoa_to_sheet([['ONE SHOT · MISIÓN TERRITORIAL'],['Generada',new Date().toISOString()],['Evidencias existentes',rows.length],['Perímetro GeoJSON',JSON.stringify({type:'Polygon',coordinates:[S.area.map(([a,b])=>[b,a])]})]]),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,ws,'DATOS_TECNICOS');XLSX.utils.book_append_sheet(book,cfg,'MISION_CONFIG');XLSX.writeFile(book,`ONE_SHOT_MISION_${new Date().toISOString().slice(0,10)}_${rows.length}.xlsx`)}
function bind(){
 $('fileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{notice(`Leyendo ${f.name} sin bloquear la página…`);const buf=await f.arrayBuffer(),rows=await parseExcelWorker(buf,f.name);$('importMsg').textContent=`${rows.length} registros válidos detectados · consolidando…`;let central=false;try{central=await uploadRows(rows,f.name)}catch(err){console.warn(err)}if(central){await loadCentral();$('importMsg').textContent=`✓ ${rows.length} registros procesados en la base central`}else{const by=new Map(S.all.map(r=>[r.code,r]));rows.forEach(r=>by.set(r.code,{...(by.get(r.code)||{}),...r}));S.all=[...by.values()];S.filterSig='';$('importMsg').textContent=`✓ ${rows.length} registros cargados localmente`;notice('');render({fit:true})}}catch(err){console.error(err);notice('No se pudo leer el Excel.','error');alert('No se pudo leer el Excel: '+err.message)}finally{e.target.value=''}};
 ['fProcess','fRegion','fDistrict','fType','fParty','fStatus'].forEach(id=>$(id).onchange=()=>render());let searchTimer;$('fSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>render(),160)};$('rows').onclick=e=>{const r=e.target.closest('[data-code]');if(r)openEdit(r.dataset.code)};$('editForm').onsubmit=e=>{e.preventDefault();saveCurrent()};$('fitBtn').onclick=()=>{const pts=S.visible.filter(validPoint).map(r=>[+r.latitude,+r.longitude]);if(pts.length)S.map.fitBounds(pts,{padding:[20,20],maxZoom:16})};$('clearAreaBtn').onclick=clearArea;$('missionBtn').onclick=exportMission;$('reloadBtn').onclick=()=>loadCentral();
}
async function boot(){if(S.booted)return;S.booted=true;try{notice('Preparando mapa…');await new Promise(r=>setTimeout(r,30));initMap();bind();status('● Listo','#93c5fd');notice('Mapa listo. Conectando con la base central…');setTimeout(()=>loadCentral(),80);console.info('[ONE SHOT CONTROL]',BUILD)}catch(e){console.error(e);status('● Error','#fca5a5');notice('No se pudo iniciar el mapa. Recarga la página; si continúa, abre en una ventana nueva.','error');$('importMsg').textContent=e.message}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0),{once:true});else setTimeout(boot,0);
})();