'use strict';
const SUPA_URL='https://jdupbwkbitkcwhnsslkk.supabase.co',SUPA_KEY='sb_publishable_j8mj7pLl_Bt713wzmG0oKg_lKfphiO3';
const db=window.supabase?.createClient(SUPA_URL,SUPA_KEY),S={all:[],visible:[],selected:[],current:null,markers:new Map(),area:null,source:''};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const map=L.map('map').setView([-9.2,-75.0],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(map);const drawn=new L.FeatureGroup().addTo(map);map.addControl(new L.Control.Draw({draw:{polyline:false,rectangle:false,circle:false,circlemarker:false,marker:false,polygon:{allowIntersection:false,showArea:true}},edit:{featureGroup:drawn,remove:true}}));
map.on(L.Draw.Event.CREATED,e=>{drawn.clearLayers();drawn.addLayer(e.layer);S.area=e.layer.toGeoJSON().geometry.coordinates[0].map(([x,y])=>[y,x]);selectArea()});map.on(L.Draw.Event.EDITED,e=>{const l=[...e.layers.getLayers()][0];if(l){S.area=l.toGeoJSON().geometry.coordinates[0].map(([x,y])=>[y,x]);selectArea()}});map.on(L.Draw.Event.DELETED,clearArea);
function norm(v){return String(v??'').trim()}function statusOf(r){return norm(r.review_status||r.status||r.TIPO)==='PENDIENTE'?'PENDIENTE':norm(r.review_status||'REVISADO')||'REVISADO'}
function color(r){return statusOf(r)==='PENDIENTE'?'#ef4444':statusOf(r)==='ACTUALIZAR'?'#f59e0b':statusOf(r)==='RETIRADO'?'#64748b':'#16a34a'}
function parseExcel(buf,name){const wb=XLSX.read(buf,{type:'array'}),ws=wb.Sheets['DATOS_TECNICOS']||wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});return rows.map((x,i)=>({code:norm(x['CÓDIGO']||x.CODIGO||x.ID||`ROW-${i+1}`),verifier:norm(x['VERIFICADOR']),capture_date:norm(x['FECHA']),capture_time:norm(x['HORA']),latitude:+x['LATITUD'],longitude:+x['LONGITUD'],gps_accuracy:+x['GPS ±m']||null,altitude:+x['ALTITUD']||null,ubigeo:norm(x['UBIGEO']),region:norm(x['REGIÓN']),province:norm(x['PROVINCIA']),district:norm(x['DISTRITO']),address:norm(x['DIRECCIÓN CAPTURA']),type:norm(x['TIPO']||'PENDIENTE'),party:norm(x['PARTIDO']),provider:norm(x['EMPRESA / PROVEEDOR']),process:norm(x['PROCESO']),orientation:norm(x['ORIENTACIÓN CAPTURA']),pipeline:norm(x['PIPELINE']),sha_original:norm(x['SHA-256 ORIGINAL']),sha_marked:norm(x['SHA-256 MARCADA']),review_status:norm(x['TIPO'])==='PENDIENTE'?'PENDIENTE':'REVISADO',source_file:name,notes:''})).filter(r=>Number.isFinite(r.latitude)&&Number.isFinite(r.longitude));}
async function uploadRows(rows,name){if(!db) return false;const payload=rows.map(r=>({...r,updated_at:new Date().toISOString()}));const {error}=await db.from('control_evidences').upsert(payload,{onConflict:'code'});if(error)throw error;await db.from('control_imports').insert({file_name:name,row_count:rows.length});return true}
async function loadCentral(){try{const {data,error}=await db.from('control_evidences').select('*').order('capture_date',{ascending:false}).limit(20000);if(error)throw error;S.all=data||[];$('syncBadge').textContent='● Central conectado';$('syncBadge').style.color='#8ff0b5';$('importMsg').textContent=`Base central · ${S.all.length} evidencias`;render()}catch(e){$('syncBadge').textContent='● Modo local';$('importMsg').textContent='Base central aún no disponible · puedes trabajar con Excel local';console.warn(e)}}
function unique(field){return [...new Set(S.all.map(r=>norm(r[field])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}function fillSelect(id,field,label){const el=$(id),cur=el.value;el.innerHTML=`<option value="">${label}</option>`+unique(field).map(x=>`<option>${esc(x)}</option>`).join('');el.value=cur}
function filtered(){const get=id=>norm($(id).value),q=get('fSearch').toLowerCase();return S.all.filter(r=>(!get('fProcess')||r.process===get('fProcess'))&&(!get('fRegion')||r.region===get('fRegion'))&&(!get('fDistrict')||r.district===get('fDistrict'))&&(!get('fType')||r.type===get('fType'))&&(!get('fParty')||r.party===get('fParty'))&&(!get('fStatus')||statusOf(r)===get('fStatus'))&&(!q||JSON.stringify([r.code,r.address,r.party,r.district,r.type]).toLowerCase().includes(q)))}
function render(){S.visible=filtered();['fProcess','fRegion','fDistrict','fType','fParty'].forEach((id,i)=>fillSelect(id,['process','region','district','type','party'][i],[ 'Proceso · Todos','Región · Todas','Distrito · Todos','Tipo · Todos','Partido · Todos'][i]));$('kTotal').textContent=S.all.length;$('kPending').textContent=S.all.filter(r=>statusOf(r)==='PENDIENTE').length;$('kDistricts').textContent=new Set(S.all.map(r=>r.district).filter(Boolean)).size;$('sideCount').textContent=`${S.visible.length} visibles`;paintMap();paintRows()}
function paintMap(){for(const m of S.markers.values())m.remove();S.markers.clear();const pts=[];S.visible.forEach(r=>{const m=L.circleMarker([r.latitude,r.longitude],{radius:7,color:'#fff',weight:2,fillColor:color(r),fillOpacity:.95}).addTo(map).bindPopup(`<div class="pop"><b>${esc(r.code)}</b><small>${esc(r.type)} · ${esc(r.party||'Sin partido')}</small><small>${esc(r.address)}</small><small>${esc(statusOf(r))}</small></div>`);m.on('click',()=>openEdit(r.code));S.markers.set(r.code,m);pts.push([r.latitude,r.longitude])});if(pts.length&&S.all.length===S.visible.length&&map.getZoom()<6)map.fitBounds(pts,{padding:[20,20],maxZoom:15})}
function paintRows(){const h=S.visible.slice(0,600).map(r=>`<div class="row ${S.current?.code===r.code?'on':''}" data-code="${esc(r.code)}"><b>${esc(r.code)} · ${esc(r.type)}</b><span>${esc(r.party||'Sin partido')} · ${esc(r.district||'Distrito pendiente')}</span><span>${esc(r.address)}</span></div>`).join('');$('rows').innerHTML=h||'<div class="empty">Sin resultados.</div>'}
function openEdit(code){const r=S.all.find(x=>x.code===code);if(!r)return;S.current=r;$('editorEmpty').classList.add('hidden');$('editForm').classList.remove('hidden');$('eCode').textContent=r.code;$('eType').value=r.type||'';$('eParty').value=r.party||'';$('eDistrict').value=r.district||'';$('eStatus').value=statusOf(r);$('eNotes').value=r.notes||'';paintRows();S.markers.get(code)?.openPopup()}
async function saveCurrent(){if(!S.current)return;Object.assign(S.current,{type:norm($('eType').value),party:norm($('eParty').value),district:norm($('eDistrict').value),review_status:norm($('eStatus').value),notes:norm($('eNotes').value),updated_at:new Date().toISOString()});try{if(S.current.id){await db.from('control_evidences').update({type:S.current.type,party:S.current.party,district:S.current.district,review_status:S.current.review_status,notes:S.current.notes,updated_at:S.current.updated_at}).eq('id',S.current.id)}}catch(e){console.warn(e)}const i=S.visible.findIndex(x=>x.code===S.current.code);render();if(i>=0&&S.visible[i+1])openEdit(S.visible[i+1].code)}
function pip(p,poly){let x=p[1],y=p[0],inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let xi=poly[i][1],yi=poly[i][0],xj=poly[j][1],yj=poly[j][0],hit=((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi||1e-12)+xi);if(hit)inside=!inside}return inside}
function selectArea(){S.selected=S.visible.filter(r=>pip([r.latitude,r.longitude],S.area));$('kSelected').textContent=S.selected.length;$('missionBtn').disabled=!S.selected.length;S.selected.forEach(r=>S.markers.get(r.code)?.setStyle({radius:10,weight:4}));$('importMsg').textContent=`Perímetro: ${S.selected.length} evidencias existentes. Exporta la misión para trabajo de campo.`}
function clearArea(){S.area=null;S.selected=[];drawn.clearLayers();$('kSelected').textContent='0';$('missionBtn').disabled=true;paintMap()}
function exportMission(){if(!S.selected.length)return;const rows=S.selected.map(r=>({'CÓDIGO':r.code,'FECHA':r.capture_date,'HORA':r.capture_time,'LATITUD':r.latitude,'LONGITUD':r.longitude,'GPS ±m':r.gps_accuracy,'REGIÓN':r.region,'PROVINCIA':r.province,'DISTRITO':r.district,'DIRECCIÓN CAPTURA':r.address,'TIPO':r.type,'PARTIDO':r.party,'PROCESO':r.process,'ESTADO MISIÓN':'REVISAR / ACTUALIZAR','OBSERVACIÓN CAMPO':''}));const ws=XLSX.utils.json_to_sheet(rows),cfg=XLSX.utils.aoa_to_sheet([['ONE SHOT · MISIÓN TERRITORIAL'],['Generada',new Date().toISOString()],['Evidencias existentes',rows.length],['Perímetro GeoJSON',JSON.stringify({type:'Polygon',coordinates:[S.area.map(([a,b])=>[b,a])]})]]),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,ws,'DATOS_TECNICOS');XLSX.utils.book_append_sheet(book,cfg,'MISION_CONFIG');XLSX.writeFile(book,`ONE_SHOT_MISION_${new Date().toISOString().slice(0,10)}_${rows.length}.xlsx`)}
$('fileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const rows=parseExcel(await f.arrayBuffer(),f.name);$('importMsg').textContent=`${rows.length} registros válidos detectados · consolidando...`;let central=false;try{central=await uploadRows(rows,f.name)}catch(err){console.warn(err)}if(central){await loadCentral();$('importMsg').textContent=`✓ ${rows.length} registros procesados en la base central`}else{const by=new Map(S.all.map(r=>[r.code,r]));rows.forEach(r=>by.set(r.code,{...(by.get(r.code)||{}),...r}));S.all=[...by.values()];$('importMsg').textContent=`✓ ${rows.length} registros cargados localmente`;render()}}catch(err){alert('No se pudo leer el Excel: '+err.message)}e.target.value=''};
['fProcess','fRegion','fDistrict','fType','fParty','fStatus'].forEach(id=>$(id).onchange=render);$('fSearch').oninput=render;$('rows').onclick=e=>{const r=e.target.closest('[data-code]');if(r)openEdit(r.dataset.code)};$('editForm').onsubmit=e=>{e.preventDefault();saveCurrent()};$('fitBtn').onclick=()=>{const pts=S.visible.map(r=>[r.latitude,r.longitude]);if(pts.length)map.fitBounds(pts,{padding:[20,20],maxZoom:16})};$('clearAreaBtn').onclick=clearArea;$('missionBtn').onclick=exportMission;$('reloadBtn').onclick=loadCentral;loadCentral();