'use strict';
(()=>{
const BUILD='control-v0.3.0-594';
const SUPA_URL='https://jdupbwkbitkcwhnsslkk.supabase.co';
const SUPA_KEY='sb_publishable_j8mj7pLl_Bt713wzmG0oKg_lKfphiO3';
const MAX_MARKERS=1200,MAX_ROWS=300;
const S={all:[],visible:[],selected:[],current:null,map:null,markerLayer:null,markers:new Map(),drawing:false,areaPoints:[],areaLine:null,areaPolygon:null,filterSig:'',renderToken:0};
const $=id=>document.getElementById(id),norm=v=>String(v??'').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const valid=r=>Number.isFinite(+r.latitude)&&Number.isFinite(+r.longitude)&&Math.abs(+r.latitude)<=90&&Math.abs(+r.longitude)<=180&&(+r.latitude!==0||+r.longitude!==0);
const statusOf=r=>norm(r.review_status||r.status||r.type)==='PENDIENTE'?'PENDIENTE':norm(r.review_status||'REVISADO')||'REVISADO';
const pointColor=r=>statusOf(r)==='PENDIENTE'?'#ef4444':statusOf(r)==='ACTUALIZAR'?'#f59e0b':statusOf(r)==='RETIRADO'?'#64748b':'#16a34a';
function msg(text){$('importMsg').textContent=text}
function badge(text,color=''){$('syncBadge').textContent=text;$('syncBadge').style.color=color}
function notice(text,tone='info'){const n=$('bootNotice');if(!n)return;n.hidden=!text;n.textContent=text;n.dataset.tone=tone}
function rest(path,opts={}){return fetch(SUPA_URL+'/rest/v1/'+path,{...opts,headers:{apikey:SUPA_KEY,Authorization:'Bearer '+SUPA_KEY,'Content-Type':'application/json',...(opts.headers||{})}})}
function initMap(){if(!window.L)throw new Error('No cargó Leaflet');$('map').innerHTML='';S.map=L.map('map',{preferCanvas:true,zoomControl:true}).setView([-9.2,-75],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap',updateWhenIdle:true,keepBuffer:1}).addTo(S.map);S.markerLayer=L.layerGroup().addTo(S.map);S.map.on('click',e=>{if(!S.drawing)return;S.areaPoints.push([e.latlng.lat,e.latlng.lng]);paintAreaDraft();$('finishAreaBtn').disabled=S.areaPoints.length<3;$('mapHint').textContent=`Zona: ${S.areaPoints.length} puntos · sigue marcando o pulsa Finalizar`;});}
function unique(field){return [...new Set(S.all.map(r=>norm(r[field])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function refreshFilters(){const sig=[S.all.length,...['process','region','district','type','party'].map(f=>unique(f).join('|'))].join('§');if(sig===S.filterSig)return;S.filterSig=sig;[['fProcess','process','Proceso · Todos'],['fRegion','region','Región · Todas'],['fDistrict','district','Distrito · Todos'],['fType','type','Tipo · Todos'],['fParty','party','Partido · Todos']].forEach(([id,field,label])=>{const el=$(id),cur=el.value;el.innerHTML=`<option value="">${label}</option>`+unique(field).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');el.value=cur})}
function applyFilters(){const v=id=>norm($(id).value),q=v('fSearch').toLowerCase();S.visible=S.all.filter(r=>(!v('fProcess')||r.process===v('fProcess'))&&(!v('fRegion')||r.region===v('fRegion'))&&(!v('fDistrict')||r.district===v('fDistrict'))&&(!v('fType')||r.type===v('fType'))&&(!v('fParty')||r.party===v('fParty'))&&(!v('fStatus')||statusOf(r)===v('fStatus'))&&(!q||[r.code,r.address,r.party,r.district,r.type].join(' ').toLowerCase().includes(q)))}
function paintRows(){const list=S.visible.slice(0,MAX_ROWS);$('rows').innerHTML=list.map(r=>`<div class="row ${S.current?.code===r.code?'on':''}" data-code="${esc(r.code)}"><b>${esc(r.code)} · ${esc(r.type)}</b><span>${esc(r.party||'Sin partido')} · ${esc(r.district||'Distrito pendiente')}</span><span>${esc(r.address)}</span></div>`).join('')||'<div class="empty">Sin resultados.</div>'}
function paintMarkers(fit=false){if(!S.map||!S.markerLayer)return;const token=++S.renderToken;S.markerLayer.clearLayers();S.markers.clear();const list=S.visible.filter(valid).slice(0,MAX_MARKERS),pts=[];let i=0;function chunk(){if(token!==S.renderToken)return;const end=Math.min(i+150,list.length);for(;i<end;i++){const r=list[i],m=L.circleMarker([+r.latitude,+r.longitude],{radius:7,color:'#fff',weight:2,fillColor:pointColor(r),fillOpacity:.95});m.bindPopup(`<div class="pop"><b>${esc(r.code)}</b><small>${esc(r.type)} · ${esc(r.party||'Sin partido')}</small><small>${esc(r.address)}</small><small>${esc(statusOf(r))}</small></div>`);m.on('click',()=>openEdit(r.code));S.markerLayer.addLayer(m);S.markers.set(r.code,m);pts.push([+r.latitude,+r.longitude]);}if(i<list.length)setTimeout(chunk,0);else if(fit&&pts.length)S.map.fitBounds(pts,{padding:[20,20],maxZoom:15});}
chunk();if(S.visible.length>MAX_MARKERS)$('mapHint').textContent=`Mostrando ${MAX_MARKERS} de ${S.visible.length} puntos · aplica filtros para afinar`;}
function render(fit=false){refreshFilters();applyFilters();$('kTotal').textContent=S.all.length;$('kPending').textContent=S.all.filter(r=>statusOf(r)==='PENDIENTE').length;$('kDistricts').textContent=new Set(S.all.map(r=>r.district).filter(Boolean)).size;$('sideCount').textContent=`${S.visible.length} visibles`;paintRows();paintMarkers(fit)}
function openEdit(code){const r=S.all.find(x=>x.code===code);if(!r)return;S.current=r;$('editorEmpty').classList.add('hidden');$('editForm').classList.remove('hidden');$('eCode').textContent=r.code;$('eType').value=r.type||'';$('eParty').value=r.party||'';$('eDistrict').value=r.district||'';$('eStatus').value=statusOf(r);$('eNotes').value=r.notes||'';paintRows();S.markers.get(code)?.openPopup()}
async function saveCurrent(){if(!S.current)return;Object.assign(S.current,{type:norm($('eType').value),party:norm($('eParty').value),district:norm($('eDistrict').value),review_status:norm($('eStatus').value),notes:norm($('eNotes').value),updated_at:new Date().toISOString()});try{if(S.current.id){await rest(`control_evidences?id=eq.${encodeURIComponent(S.current.id)}`,{method:'PATCH',body:JSON.stringify({type:S.current.type,party:S.current.party,district:S.current.district,review_status:S.current.review_status,notes:S.current.notes,updated_at:S.current.updated_at}),headers:{Prefer:'return=minimal'}})}}catch(e){console.warn(e)}const idx=S.visible.findIndex(x=>x.code===S.current.code);render(false);if(idx>=0&&S.visible[idx+1])openEdit(S.visible[idx+1].code)}
async function loadCentral(){badge('● Conectando…','#facc15');msg('Leyendo base central…');try{const r=await rest('control_evidences?select=*&order=capture_date.desc&limit=5000');if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();S.all=(data||[]).filter(valid);S.filterSig='';badge('● Central conectado','#8ff0b5');msg(`Base central · ${S.all.length} evidencias`);notice('');render(true)}catch(e){console.warn(e);badge('● Modo local');msg('Base central no disponible · puedes subir un Excel');notice('El dashboard sigue disponible en modo local.','warn')}}
function startArea(){S.drawing=true;S.areaPoints=[];clearAreaLayers();$('drawAreaBtn').disabled=true;$('finishAreaBtn').disabled=true;$('mapHint').textContent='Haz clic en el mapa para marcar el perímetro';}
function paintAreaDraft(){clearAreaLayers(false);if(S.areaPoints.length>=2)S.areaLine=L.polyline(S.areaPoints,{color:'#2563eb',weight:3,dashArray:'6 5'}).addTo(S.map);S.areaPoints.forEach((p,i)=>L.circleMarker(p,{radius:5,color:i===0?'#16a34a':'#2563eb',fillOpacity:1}).addTo(S.map)._oneShotAreaPoint=true)}
function clearAreaLayers(clearPoints=true){if(S.areaLine){S.map.removeLayer(S.areaLine);S.areaLine=null}if(S.areaPolygon){S.map.removeLayer(S.areaPolygon);S.areaPolygon=null}S.map.eachLayer(l=>{if(l._oneShotAreaPoint)S.map.removeLayer(l)});if(clearPoints)S.areaPoints=[]}
function finishArea(){if(S.areaPoints.length<3)return;S.drawing=false;clearAreaLayers(false);S.areaPolygon=L.polygon(S.areaPoints,{color:'#2563eb',weight:3,fillOpacity:.08}).addTo(S.map);$('drawAreaBtn').disabled=false;$('finishAreaBtn').disabled=true;selectArea();}
function pip(lat,lng,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const yi=poly[i][0],xi=poly[i][1],yj=poly[j][0],xj=poly[j][1];const hit=((yi>lat)!=(yj>lat))&&(lng<(xj-xi)*(lat-yi)/(yj-yi||1e-12)+xi);if(hit)inside=!inside}return inside}
function selectArea(){S.selected=S.visible.filter(r=>pip(+r.latitude,+r.longitude,S.areaPoints));$('kSelected').textContent=S.selected.length;$('missionBtn').disabled=!S.selected.length;$('mapHint').textContent=`Perímetro listo · ${S.selected.length} evidencias dentro`;for(const r of S.selected)S.markers.get(r.code)?.setStyle({radius:10,weight:4});msg(`Perímetro: ${S.selected.length} evidencias existentes.`)}
function clearArea(){S.drawing=false;clearAreaLayers(true);S.selected=[];$('kSelected').textContent='0';$('missionBtn').disabled=true;$('drawAreaBtn').disabled=false;$('finishAreaBtn').disabled=true;$('mapHint').textContent='✎ Dibuja una zona para crear una misión';paintMarkers(false)}
function loadScript(src){return new Promise((resolve,reject)=>{if(window.XLSX)return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('No se pudo cargar la librería Excel'));document.head.appendChild(s)})}
function mapExcelRow(x,i,name){return {code:norm(x['CÓDIGO']||x.CODIGO||x.ID||`ROW-${i+1}`),verifier:norm(x['VERIFICADOR']),capture_date:norm(x['FECHA']),capture_time:norm(x['HORA']),latitude:+x['LATITUD'],longitude:+x['LONGITUD'],gps_accuracy:+x['GPS ±m']||null,altitude:+x['ALTITUD']||null,ubigeo:norm(x['UBIGEO']),region:norm(x['REGIÓN']),province:norm(x['PROVINCIA']),district:norm(x['DISTRITO']),address:norm(x['DIRECCIÓN CAPTURA']),type:norm(x['TIPO']||'PENDIENTE'),party:norm(x['PARTIDO']),provider:norm(x['EMPRESA / PROVEEDOR']),process:norm(x['PROCESO']),orientation:norm(x['ORIENTACIÓN CAPTURA']),pipeline:norm(x['PIPELINE']),sha_original:norm(x['SHA-256 ORIGINAL']),sha_marked:norm(x['SHA-256 MARCADA']),review_status:norm(x['TIPO'])==='PENDIENTE'?'PENDIENTE':'REVISADO',source_file:name,notes:''}}
async function readExcel(file){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellStyles:false,cellFormula:false,cellHTML:false}),ws=wb.Sheets['DATOS_TECNICOS']||wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});return raw.map((x,i)=>mapExcelRow(x,i,file.name)).filter(valid)}
async function uploadRows(rows,name){const chunk=250;for(let i=0;i<rows.length;i+=chunk){msg(`Consolidando ${Math.min(i+chunk,rows.length)} de ${rows.length}…`);const body=rows.slice(i,i+chunk).map(r=>({...r,updated_at:new Date().toISOString()}));const res=await rest('control_evidences?on_conflict=code',{method:'POST',body:JSON.stringify(body),headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});if(!res.ok)throw new Error('No se pudo consolidar: HTTP '+res.status);await new Promise(r=>setTimeout(r,0))}await rest('control_imports',{method:'POST',body:JSON.stringify({file_name:name,row_count:rows.length}),headers:{Prefer:'return=minimal'}})}
async function exportMission(){if(!S.selected.length)return;await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');const rows=S.selected.map(r=>({'CÓDIGO':r.code,'FECHA':r.capture_date,'HORA':r.capture_time,'LATITUD':r.latitude,'LONGITUD':r.longitude,'GPS ±m':r.gps_accuracy,'REGIÓN':r.region,'PROVINCIA':r.province,'DISTRITO':r.district,'DIRECCIÓN CAPTURA':r.address,'TIPO':r.type,'PARTIDO':r.party,'PROCESO':r.process,'ESTADO MISIÓN':'REVISAR / ACTUALIZAR','OBSERVACIÓN CAMPO':''})),ws=XLSX.utils.json_to_sheet(rows),cfg=XLSX.utils.aoa_to_sheet([['ONE SHOT · MISIÓN TERRITORIAL'],['Generada',new Date().toISOString()],['Evidencias existentes',rows.length],['Perímetro GeoJSON',JSON.stringify({type:'Polygon',coordinates:[[...S.areaPoints.map(([a,b])=>[b,a]),[S.areaPoints[0][1],S.areaPoints[0][0]]]})]]),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,ws,'DATOS_TECNICOS');XLSX.utils.book_append_sheet(book,cfg,'MISION_CONFIG');XLSX.writeFile(book,`ONE_SHOT_MISION_${new Date().toISOString().slice(0,10)}_${rows.length}.xlsx`)}
function bind(){['fProcess','fRegion','fDistrict','fType','fParty','fStatus'].forEach(id=>$(id).onchange=()=>render(false));let t;$('fSearch').oninput=()=>{clearTimeout(t);t=setTimeout(()=>render(false),220)};$('rows').onclick=e=>{const row=e.target.closest('[data-code]');if(row)openEdit(row.dataset.code)};$('editForm').onsubmit=e=>{e.preventDefault();saveCurrent()};$('fitBtn').onclick=()=>{const pts=S.visible.filter(valid).map(r=>[+r.latitude,+r.longitude]);if(pts.length)S.map.fitBounds(pts,{padding:[20,20],maxZoom:16})};$('drawAreaBtn').onclick=startArea;$('finishAreaBtn').onclick=finishArea;$('clearAreaBtn').onclick=clearArea;$('missionBtn').onclick=exportMission;$('reloadBtn').onclick=loadCentral;$('fileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{notice(`Leyendo ${f.name}…`);const rows=await readExcel(f);msg(`${rows.length} registros válidos detectados · consolidando…`);try{await uploadRows(rows,f.name);await loadCentral();msg(`✓ ${rows.length} registros procesados en la base central`)}catch(syncErr){console.warn(syncErr);const by=new Map(S.all.map(r=>[r.code,r]));rows.forEach(r=>by.set(r.code,{...(by.get(r.code)||{}),...r}));S.all=[...by.values()];S.filterSig='';render(true);msg(`✓ ${rows.length} registros cargados localmente`)}notice('')}catch(err){console.error(err);notice('No se pudo leer el Excel.','error');alert(err.message)}finally{e.target.value=''}}}
function boot(){try{notice('Preparando mapa…');initMap();bind();badge('● Listo','#93c5fd');notice('');setTimeout(loadCentral,120);console.info('[ONE SHOT CONTROL]',BUILD)}catch(e){console.error(e);badge('● Error','#fca5a5');notice('No se pudo iniciar el panel.','error');msg(e.message)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();