'use strict';
(()=>{
const BUILD='control-v6.20-shared-catalogs';
let CFG=null,C={processes:[],parties:[],offices:[],candidates:[],providers:[],types:[]},enhancing=false;
const $=id=>document.getElementById(id),norm=v=>String(v??'').trim(),lower=v=>norm(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const slug=s=>norm(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'');
const operator=()=>norm(localStorage.getItem('oneShotControlOperator'))||'Operador CONTROL';
async function config(){if(CFG)return CFG;const src=[...document.scripts].map(s=>s.src).find(s=>/\/control\/app\.js/.test(s))||'app.js';const text=await fetch(src,{cache:'no-store'}).then(r=>r.text()),u=(text.match(/SUPA_URL='([^']+)'/)||[])[1],k=(text.match(/SUPA_KEY='([^']+)'/)||[])[1];if(!u||!k)throw new Error('Configuración central no disponible');return CFG={url:u,key:k}}
async function api(path,opts={}){const c=await config();return fetch(`${c.url}/rest/v1/${path}`,{...opts,headers:{apikey:c.key,Authorization:'Bearer '+c.key,'Content-Type':'application/json',...(opts.headers||{})}})}
async function get(path){const r=await api(path);if(!r.ok)throw new Error(`Catálogo HTTP ${r.status}`);return r.json()}
async function loadCatalogs(){const [processes,parties,offices,candidates,providers,types]=await Promise.all([
 get('catalog_processes?select=*&active=eq.true&order=sort_order,name'),get('catalog_parties?select=*&active=eq.true&order=sort_order,name'),get('catalog_offices?select=*&active=eq.true&order=sort_order,name'),get('catalog_candidates?select=*&active=eq.true&order=sort_order,full_name'),get('catalog_providers?select=*&active=eq.true&order=legal_name'),get('catalog_evidence_types?select=*&active=eq.true&order=sort_order,name')]);
 C={processes,parties,offices,candidates,providers,types};window.ONE_SHOT_SHARED_CATALOGS=C;window.dispatchEvent(new CustomEvent('oneshot:catalogs',{detail:C}));return C}
function opt(list,value,label,idFn=x=>x.id){return list.map(x=>`<option value="${esc(value(x))}" data-id="${esc(idFn(x)||'')}">${esc(label(x))}</option>`).join('')}
function buildSelect(old,list,current,placeholder,value=x=>x.name,label=x=>x.name,idFn=x=>x.id){if(!old)return null;const s=document.createElement('select');s.id=old.id;s.className=old.className;s.innerHTML=`<option value="">${placeholder}</option>`+opt(list,value,label,idFn);const exists=list.some(x=>String(value(x))===String(current));if(current&&!exists){const o=document.createElement('option');o.value=current;o.textContent=`⚠ ${current} · fuera de catálogo`;o.dataset.id='';s.appendChild(o)}s.value=current||'';old.replaceWith(s);return s}
function installQuickFields(){const t=$('eType'),p=$('eParty');if(t&&t.tagName!=='SELECT')buildSelect(t,C.types,t.value,'Tipo pendiente',x=>x.code,x=>x.name,x=>x.code);if(p&&p.tagName!=='SELECT')buildSelect(p,C.parties,p.value,'Partido pendiente',x=>x.name,x=>x.name)}
function codeSelected(){return document.querySelector('.reviewItem.on[data-rv]')?.dataset.rv||norm($('eCode')?.textContent)}
async function evidence(code){if(!code)return null;const r=await api(`control_evidences?select=*&code=eq.${encodeURIComponent(code)}&limit=1`);if(!r.ok)return null;return (await r.json())[0]||null}
function selectedId(id){const s=$(id),o=s?.selectedOptions?.[0];return o?.dataset?.id||null}
function rebuildDependent(r){const procId=selectedId('opProcess')||r.process_id||null,partyId=selectedId('opParty')||r.party_id||null;
 const oldOffice=$('opOffice');if(oldOffice){const cur=oldOffice.value,items=C.offices.filter(x=>!x.process_id||!procId||x.process_id===procId);buildSelect(oldOffice,items,cur,'Cargo pendiente',x=>x.name,x=>x.name)}
 const oldCandidate=$('opCandidate');if(oldCandidate){const cur=oldCandidate.value,items=C.candidates.filter(x=>(!partyId||x.party_id===partyId)&&(!procId||x.process_id===procId));buildSelect(oldCandidate,items,cur,items.length?'Candidato pendiente':'Sin candidatos cargados',x=>x.display_name||x.full_name,x=>x.display_name||x.full_name);}
}
function quality(record){const type=$('opType')?.value||record.type||'',rule=C.types.find(x=>x.code===type)||{},flags=[];let score=100;
 if(!record.photo_path){flags.push('SIN_FOTO');score-=25}
 if(!Number.isFinite(+record.latitude)||!Number.isFinite(+record.longitude)){flags.push('GPS_INVALIDO');score-=30}
 else if(Number(record.gps_accuracy)>30){flags.push('GPS_BAJA_PRECISION');score-=10}
 if(!norm($('opDistrict')?.value||record.district)){flags.push('DISTRITO_PENDIENTE');score-=15}
 if(rule.requires_party&&!norm($('opParty')?.value)){flags.push('PARTIDO_PENDIENTE');score-=15}
 if(rule.requires_provider&&!norm($('opProvider')?.value)){flags.push('PROVEEDOR_PENDIENTE');score-=10}
 if(!record.sha_original){flags.push('SHA_ORIGINAL_PENDIENTE');score-=8}
 if(!record.sha_marked){flags.push('SHA_MARCADA_PENDIENTE');score-=5}
 return{score:Math.max(0,score),flags}
}
function paintQuality(record){const host=$('catalogQuality');if(!host)return;const q=quality(record),tone=q.score>=90?'ok':q.score>=70?'warn':'bad';host.className=`catalogQuality ${tone}`;host.innerHTML=`<div><b>Calidad ${q.score}/100</b><span>${q.flags.length?q.flags.join(' · '):'Evidencia completa para validación'}</span></div><strong>${q.score>=90?'✓':q.score>=70?'!':'×'}</strong>`}
async function audit(code,action,changes){await api('control_audit_log',{method:'POST',body:JSON.stringify({entity_type:'EVIDENCE',entity_id:code,action,actor:operator(),changes}),headers:{Prefer:'return=minimal'}}).catch(()=>{})}
async function patchCatalogIds(record){const q=quality(record),patch={
 process_id:selectedId('opProcess'),party_id:selectedId('opParty'),candidate_id:selectedId('opCandidate'),office_id:selectedId('opOffice'),provider_id:selectedId('opProvider'),evidence_type_code:$('opType')?.value||null,data_quality_score:q.score,validation_flags:q.flags,validated_by:operator(),validated_at:q.flags.length?null:new Date().toISOString()
 };
 const r=await api(`control_evidences?code=eq.${encodeURIComponent(record.code)}`,{method:'PATCH',body:JSON.stringify(patch),headers:{Prefer:'return=minimal'}});if(!r.ok)throw new Error(`No se pudo guardar catálogo (${r.status})`);await audit(record.code,'CATALOG_VALIDATE',{catalogs:patch});return q}
async function enhanceEditor(){if(enhancing)return;const host=$('editorOps'),code=codeSelected();if(!host||!code||host.dataset.catalogCode===code)return;enhancing=true;try{const r=await evidence(code);if(!r)return;host.dataset.catalogCode=code;
 let t=$('opType');if(t&&t.tagName!=='SELECT')t=buildSelect(t,C.types,r.evidence_type_code||r.type,'Tipo pendiente',x=>x.code,x=>x.name,x=>x.code);
 let p=$('opParty');if(p&&p.tagName!=='SELECT')p=buildSelect(p,C.parties,r.party||'','Partido pendiente',x=>x.name,x=>x.logo_url?`▣ ${x.name}`:x.name);
 let pr=$('opProvider');if(pr&&pr.tagName!=='SELECT')pr=buildSelect(pr,C.providers,r.provider||'','Proveedor pendiente',x=>x.trade_name||x.legal_name,x=>x.ruc?`${x.trade_name||x.legal_name} · RUC ${x.ruc}`:(x.trade_name||x.legal_name));
 let ca=$('opCandidate');if(ca&&ca.tagName!=='SELECT')ca=buildSelect(ca,C.candidates,r.candidate||'','Candidato pendiente',x=>x.display_name||x.full_name,x=>x.display_name||x.full_name);
 let of=$('opOffice');if(of&&of.tagName!=='SELECT')of=buildSelect(of,C.offices,r.office||'','Cargo pendiente',x=>x.name,x=>x.name);
 if(!$('opProcess')){const first=$('opType')?.closest('label');if(first){const lab=document.createElement('label');lab.innerHTML='<span>Proceso</span><select id="opProcess"></select>';first.parentNode.insertBefore(lab,first);const s=$('opProcess');s.innerHTML='<option value="">Proceso pendiente</option>'+opt(C.processes,x=>x.code,x=>x.name);const proc=C.processes.find(x=>x.id===r.process_id)||C.processes.find(x=>lower(x.code)===lower(r.process));s.value=proc?.code||'';}}
 rebuildDependent(r);
 ['opProcess','opParty'].forEach(id=>$(id)?.addEventListener('change',()=>{rebuildDependent(r);paintQuality(r)}));['opType','opProvider','opDistrict','opCandidate','opOffice'].forEach(id=>$(id)?.addEventListener('change',()=>paintQuality(r)));
 const match=$('municipalityMatch')||$('opSave');if(match&&!$('catalogQuality')){const q=document.createElement('div');q.id='catalogQuality';match.parentNode.insertBefore(q,match);}
 paintQuality(r);
 const btn=$('opSave');if(btn&&!btn.dataset.catalogWrapped){btn.dataset.catalogWrapped='1';const base=btn.onclick;btn.onclick=async ev=>{btn.disabled=true;try{await patchCatalogIds(r);if(typeof base==='function')await base.call(btn,ev)}catch(e){console.error(e);alert(e.message||e)}finally{btn.disabled=false}}}
 }finally{enhancing=false}}
function catalogHtml(){return `<div class="moduleHead"><div><h2>⚙️ Catálogos maestros</h2><p>Una sola fuente para CONTROL y ONE SHOT móvil. Evita nombres duplicados y clasificaciones libres.</p></div><button id="catalogReload" class="opsBtn secondary">↻ Actualizar</button></div><div id="catalogStats" class="miniKpis"></div><div class="catalogGrid">
 <section class="opsCard"><h3>Partidos</h3><form id="partyForm" class="catalogForm"><input id="catPartyName" placeholder="Nombre oficial" required><input id="catPartyShort" placeholder="Sigla"><input id="catPartyLogo" placeholder="URL de logo (opcional)"><button class="opsBtn">Agregar partido</button></form><div id="partyCatalog" class="catalogList"></div></section>
 <section class="opsCard"><h3>Candidatos</h3><form id="candidateForm" class="catalogForm"><select id="catCandidateProcess" required></select><select id="catCandidateParty" required></select><select id="catCandidateOffice"></select><input id="catCandidateName" placeholder="Nombre completo" required><button class="opsBtn">Agregar candidato</button></form><div id="candidateCatalog" class="catalogList"></div></section>
 <section class="opsCard"><h3>Empresas / proveedores</h3><form id="providerForm" class="catalogForm"><input id="catProviderRuc" placeholder="RUC"><input id="catProviderLegal" placeholder="Razón social" required><input id="catProviderTrade" placeholder="Nombre comercial"><button class="opsBtn">Agregar proveedor</button></form><div id="providerCatalog" class="catalogList"></div></section>
 <section class="opsCard"><h3>Reglas activas</h3><div id="typeCatalog" class="catalogList"></div></section></div>`}
function renderCatalogs(){const st=$('catalogStats');if(st)st.innerHTML=`<span>${C.parties.length}<small>Partidos</small></span><span>${C.candidates.length}<small>Candidatos</small></span><span>${C.providers.length}<small>Proveedores</small></span><span>${C.types.length}<small>Tipos</small></span>`;
 const pc=$('partyCatalog');if(pc)pc.innerHTML=C.parties.map(x=>`<div class="catalogRow"><i>${x.logo_url?`<img src="${esc(x.logo_url)}">`:esc((x.short_name||x.name).slice(0,2))}</i><div><b>${esc(x.name)}</b><span>${esc(x.short_name||x.code)}</span></div></div>`).join('');
 const cc=$('candidateCatalog');if(cc)cc.innerHTML=C.candidates.slice(0,120).map(x=>{const p=C.parties.find(y=>y.id===x.party_id),o=C.offices.find(y=>y.id===x.office_id);return`<div class="catalogRow"><i>👤</i><div><b>${esc(x.display_name||x.full_name)}</b><span>${esc(p?.name||'Partido pendiente')} · ${esc(o?.name||'Cargo pendiente')}</span></div></div>`}).join('')||'<div class="emptyOps">Todavía no hay candidatos cargados.</div>';
 const pr=$('providerCatalog');if(pr)pr.innerHTML=C.providers.slice(0,120).map(x=>`<div class="catalogRow"><i>🏢</i><div><b>${esc(x.trade_name||x.legal_name)}</b><span>${esc(x.ruc?`RUC ${x.ruc} · ${x.legal_name}`:x.legal_name)}</span></div></div>`).join('')||'<div class="emptyOps">Todavía no hay proveedores cargados.</div>';
 const ty=$('typeCatalog');if(ty)ty.innerHTML=C.types.map(x=>`<div class="catalogRule"><b>${esc(x.name)}</b><span>${x.requires_party?'Partido obligatorio · ':''}${x.requires_provider?'Proveedor obligatorio · ':''}${x.allows_tramo?'Permite tramo':''}</span></div>`).join('');
 fillAdminSelects();}
function fillAdminSelects(){const ps=$('catCandidateProcess'),pa=$('catCandidateParty'),of=$('catCandidateOffice');if(ps)ps.innerHTML='<option value="">Proceso</option>'+opt(C.processes,x=>x.id,x=>x.name);if(pa)pa.innerHTML='<option value="">Partido</option>'+opt(C.parties,x=>x.id,x=>x.name);if(of)of.innerHTML='<option value="">Cargo</option>'+opt(C.offices,x=>x.id,x=>x.name)}
async function reloadCatalogUI(){await loadCatalogs();installQuickFields();renderCatalogs();enhanceEditor()}
async function submitParty(ev){ev.preventDefault();const name=norm($('catPartyName').value),body={code:slug(name),name,short_name:norm($('catPartyShort').value)||null,logo_url:norm($('catPartyLogo').value)||null,active:true};const r=await api('catalog_parties?on_conflict=code',{method:'POST',body:JSON.stringify(body),headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});if(!r.ok)throw new Error(`Partido HTTP ${r.status}`);ev.target.reset();await reloadCatalogUI()}
async function submitCandidate(ev){ev.preventDefault();const body={process_id:$('catCandidateProcess').value||null,party_id:$('catCandidateParty').value||null,office_id:$('catCandidateOffice').value||null,full_name:norm($('catCandidateName').value),display_name:norm($('catCandidateName').value),active:true};const r=await api('catalog_candidates',{method:'POST',body:JSON.stringify(body),headers:{Prefer:'return=minimal'}});if(!r.ok)throw new Error(`Candidato HTTP ${r.status}`);ev.target.reset();await reloadCatalogUI()}
async function submitProvider(ev){ev.preventDefault();const body={ruc:norm($('catProviderRuc').value)||null,legal_name:norm($('catProviderLegal').value),trade_name:norm($('catProviderTrade').value)||null,active:true};const r=await api('catalog_providers',{method:'POST',body:JSON.stringify(body),headers:{Prefer:'return=minimal'}});if(!r.ok)throw new Error(`Proveedor HTTP ${r.status}`);ev.target.reset();await reloadCatalogUI()}
function showCatalogTab(){document.querySelectorAll('#controlTabs [data-tab]').forEach(b=>b.classList.remove('on'));$('catalogTabBtn')?.classList.add('on');['.hero','.importHub','#importProgress','#importSummary','.advancedImports','#bootNotice','.kpis','.filters','.workspace','.imports','.territorySummary'].forEach(sel=>document.querySelectorAll(sel).forEach(el=>el.style.display='none'));['reviewModule','missionsModule','casesModule'].forEach(id=>$(id)?.classList.remove('on'));$('catalogModule')?.classList.add('on');reloadCatalogUI()}
async function installCatalogModule(){const nav=$('controlTabs'),main=document.querySelector('main');if(!nav||!main||$('catalogTabBtn'))return false;const b=document.createElement('button');b.id='catalogTabBtn';b.textContent='⚙️ Catálogos';const op=nav.querySelector('.operatorBox');nav.insertBefore(b,op||null);b.onclick=showCatalogTab;nav.addEventListener('click',e=>{if(e.target.closest('[data-tab]')){$('catalogModule')?.classList.remove('on');b.classList.remove('on')}});const m=document.createElement('section');m.id='catalogModule';m.className='modulePanel';m.innerHTML=catalogHtml();main.appendChild(m);$('catalogReload').onclick=reloadCatalogUI;$('partyForm').onsubmit=e=>submitParty(e).catch(x=>alert(x.message));$('candidateForm').onsubmit=e=>submitCandidate(e).catch(x=>alert(x.message));$('providerForm').onsubmit=e=>submitProvider(e).catch(x=>alert(x.message));return true}
async function boot(){try{await loadCatalogs();installQuickFields();let n=0;const wait=setInterval(async()=>{n++;if(await installCatalogModule()||n>80)clearInterval(wait)},100);const watch=setInterval(()=>{const h=$('editorOps');if(h&&!h.__catalogWatch){h.__catalogWatch=true;new MutationObserver(()=>setTimeout(enhanceEditor,0)).observe(h,{childList:true,subtree:true});enhanceEditor();clearInterval(watch)}},120);console.info('[ONE SHOT CONTROL]',BUILD,C)}catch(e){console.warn('[CATALOGS]',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
