'use strict';
(()=>{
const BUILD='control-v6.10-ops';
const BUCKET='one-shot-evidence';
let CFG=null,rows=[],municipalities=[],missions=[],cases=[],current=null,currentCase=null;
const selected=new Set();
const $=id=>document.getElementById(id), norm=v=>String(v??'').trim(), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const lower=v=>norm(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const fmtDate=v=>v?new Date(v).toLocaleString('es-PE'):'—';
const operator=()=>norm(localStorage.getItem('oneShotControlOperator'))||'Operador CONTROL';
async function config(){if(CFG)return CFG;const src=[...document.scripts].map(s=>s.src).find(s=>/\/control\/app\.js/.test(s))||'app.js';const text=await fetch(src,{cache:'no-store'}).then(r=>r.text()),u=(text.match(/SUPA_URL='([^']+)'/)||[])[1],k=(text.match(/SUPA_KEY='([^']+)'/)||[])[1];if(!u||!k)throw new Error('Configuración central no disponible');return CFG={url:u,key:k}}
async function api(path,opts={}){const c=await config();return fetch(`${c.url}/rest/v1/${path}`,{...opts,headers:{apikey:c.key,Authorization:'Bearer '+c.key,'Content-Type':'application/json',...(opts.headers||{})}})}
const encPath=p=>String(p||'').split('/').map(encodeURIComponent).join('/');
async function mediaUrl(p){if(!p)return'';const c=await config();return `${c.url}/storage/v1/object/public/${BUCKET}/${encPath(p)}`}
async function uploadBlob(path,blob){const c=await config(),r=await fetch(`${c.url}/storage/v1/object/${BUCKET}/${encPath(path)}`,{method:'POST',headers:{apikey:c.key,Authorization:'Bearer '+c.key,'Content-Type':blob.type||'image/jpeg','x-upsert':'true'},body:blob});if(!r.ok)throw new Error(`No se pudo guardar la imagen (HTTP ${r.status})`);return path}
async function audit(entityType,entityId,action,changes){await api('control_audit_log',{method:'POST',body:JSON.stringify({entity_type:entityType,entity_id:String(entityId),action,actor:operator(),changes}),headers:{Prefer:'return=minimal'}}).catch(()=>{})}
function mapSections(){return ['.hero','.importHub','#importProgress','#importSummary','.advancedImports','#bootNotice','.kpis','.filters','.workspace','.imports','.territorySummary']}
function injectShell(){const main=document.querySelector('main');if(!main||$('controlTabs'))return;const nav=document.createElement('section');nav.id='controlTabs';nav.className='controlTabs';nav.innerHTML=`<button data-tab="map" class="on">🗺 Mapa</button><button data-tab="review">🔎 Revisión</button><button data-tab="missions">🧭 Misiones</button><button data-tab="cases">📄 Casos / Cartas</button><span class="operatorBox"><input id="controlOperator" placeholder="Operador" value="${esc(operator())}"></span>`;main.insertBefore(nav,main.firstChild);nav.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)setTab(b.dataset.tab)});$('controlOperator').addEventListener('change',e=>localStorage.setItem('oneShotControlOperator',norm(e.target.value)||'Operador CONTROL'));
 const review=document.createElement('section');review.id='reviewModule';review.className='modulePanel';review.innerHTML=reviewHtml();main.appendChild(review);
 const mis=document.createElement('section');mis.id='missionsModule';mis.className='modulePanel';mis.innerHTML=missionsHtml();main.appendChild(mis);
 const cas=document.createElement('section');cas.id='casesModule';cas.className='modulePanel';cas.innerHTML=casesHtml();main.appendChild(cas);
 const ts=document.createElement('section');ts.id='territorySummary';ts.className='territorySummary';ts.innerHTML='<div class="moduleHead"><div><h2>Resumen territorial</h2><p>Distritos con mayor carga y nivel de revisión.</p></div></div><div id="territoryGrid" class="territoryGrid"></div>';const k=document.querySelector('.kpis');k?.insertAdjacentElement('afterend',ts);
 bindModules();
}
function setTab(tab){document.querySelectorAll('#controlTabs [data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===tab));mapSections().forEach(sel=>document.querySelectorAll(sel).forEach(el=>{el.style.display=tab==='map'?'':'none'}));['reviewModule','missionsModule','casesModule'].forEach(id=>$(id)?.classList.toggle('on',id===`${tab}Module`));if(tab==='review')loadReview();if(tab==='missions')loadMissions();if(tab==='cases')loadCases()}
function reviewHtml(){return `<div class="moduleHead"><div><h2>🔎 Mesa de revisión</h2><p>Corrige foto, clasificación, partido, candidato, proveedor, ubicación y estado sin volver a la app.</p></div><div id="reviewSource" class="sourceBadge">0 seleccionadas</div></div><div class="reviewToolbar"><input id="rvSearch" placeholder="Buscar código, dirección, partido, proveedor..."><select id="rvDistrict"><option value="">Todos los distritos</option></select><select id="rvType"><option value="">Todos los tipos</option></select><select id="rvLife"><option value="">Todos los estados</option><option>NUEVA</option><option>CONFIRMADA</option><option>ACTUALIZADA</option><option>RETIRADA</option><option>NO_ENCONTRADA</option><option>PENDIENTE</option></select></div><div class="bulkBar"><b id="bulkCount">0 seleccionadas</b><select id="bulkField"><option value="lifecycle_status">Estado territorial</option><option value="type">Tipo</option><option value="party">Partido</option><option value="provider">Empresa / proveedor</option><option value="district">Distrito</option><option value="review_status">Estado revisión</option></select><input id="bulkValue" placeholder="Nuevo valor"><button id="bulkApply">Aplicar a selección</button></div><div class="opsGrid"><section class="opsCard"><h3>Evidencias</h3><div id="reviewList" class="reviewList"></div></section><section class="opsCard"><h3>Editor completo</h3><div id="editorOps" class="emptyOps">Selecciona una evidencia.</div></section></div>`}
function missionsHtml(){return `<div class="moduleHead"><div><h2>🧭 Misiones de campo</h2><p>Convierte una selección del mapa o de Revisión en trabajo asignable y medible.</p></div><button id="missionReload" class="opsBtn secondary">↻ Actualizar</button></div><div class="opsGrid"><section class="opsCard"><h3>Nueva misión</h3><div id="missionSource" class="sourceBadge">Sin selección</div><div class="missionForm"><input id="missionName" placeholder="Nombre · Ej. SAN ISIDRO 07/09"><input id="missionAssignee" placeholder="Responsable / brigada"><input id="missionObjective" placeholder="Objetivo · actualizar propaganda exterior"><input id="missionDue" type="date"><button id="missionCreate" class="opsBtn">Crear misión</button></div></section><section class="opsCard"><h3>Misiones</h3><div id="missionStats" class="miniKpis"></div><div id="missionList" class="missionList"></div></section></div>`}
function casesHtml(){return `<div class="moduleHead"><div><h2>📄 Casos, municipalidades y cartas</h2><p>Agrupa evidencias, identifica la municipalidad competente y genera un borrador de comunicación con trazabilidad.</p></div><button id="casesReload" class="opsBtn secondary">↻ Actualizar</button></div><div class="opsGrid"><section class="opsCard"><h3>Crear caso / carta</h3><div id="caseSource" class="sourceBadge">Sin selección</div><div class="caseForm"><input id="caseDistrict" placeholder="Distrito"><input id="caseSubject" placeholder="Asunto"><button id="caseCreate" class="opsBtn">Crear caso con selección</button></div><hr><h3>Catálogo municipal</h3><div class="authorityForm"><input id="authRegion" placeholder="Región"><input id="authProvince" placeholder="Provincia"><input id="authDistrict" placeholder="Distrito"><input id="authMunicipality" placeholder="Municipalidad"><input id="authName" placeholder="Nombre de autoridad"><input id="authTitle" value="ALCALDE" placeholder="Cargo"><input id="authSource" placeholder="URL de fuente oficial"><button id="authSave" class="opsBtn secondary">Guardar / actualizar autoridad</button></div><div id="authorityList" class="authorityList"></div></section><section class="opsCard"><h3>Casos</h3><div id="caseList" class="caseList"></div><h3 style="margin-top:14px">Vista de carta</h3><div id="letterPreview" class="letterPreview">Selecciona un caso.</div><div class="rowActions"><button id="letterPrint" class="opsBtn secondary">Imprimir / PDF</button><button id="caseAdvance" class="opsBtn">Avanzar estado</button></div></section></div>`}
async function fetchRows(){const out=[];for(let from=0;from<10000;from+=1000){const r=await api(`control_evidences?select=id,code,type,party,candidate,office,provider,region,province,district,address,latitude,longitude,gps_accuracy,capture_date,capture_time,review_status,lifecycle_status,notes,photo_path,photo_original_path,corrected_photo_path,correction_history,municipality_id,updated_at&order=capture_date.desc&range=${from}-${from+999}`);if(!r.ok)break;const part=await r.json();out.push(...part);if(part.length<1000)break}rows=out;renderTerritory();return rows}
function options(vals,label){return `<option value="">${label}</option>`+[...new Set(vals.map(norm).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).map(v=>`<option>${esc(v)}</option>`).join('')}
async function loadReview(){await fetchRows();$('rvDistrict').innerHTML=options(rows.map(r=>r.district),'Todos los distritos');$('rvType').innerHTML=options(rows.map(r=>r.type),'Todos los tipos');renderReview();updateSelection()}
function reviewFiltered(){const q=lower($('rvSearch')?.value),d=norm($('rvDistrict')?.value),t=norm($('rvType')?.value),l=norm($('rvLife')?.value);return rows.filter(r=>(!q||lower([r.code,r.address,r.party,r.provider,r.district,r.candidate].join(' ')).includes(q))&&(!d||r.district===d)&&(!t||r.type===t)&&(!l||norm(r.lifecycle_status||'NUEVA')===l))}
async function renderReview(){const list=reviewFiltered().slice(0,700),host=$('reviewList');host.innerHTML=list.map(r=>`<article class="reviewItem ${current?.code===r.code?'on':''}" data-rv="${esc(r.code)}"><input type="checkbox" data-check="${esc(r.code)}" ${selected.has(r.code)?'checked':''}><img data-thumb="${esc(r.photo_path||'')}" alt=""><div><b>${esc(r.code)} · ${esc(r.type||'PENDIENTE')}</b><span>${esc(r.party||'Partido pendiente')} · ${esc(r.provider||'Proveedor pendiente')}</span><span>${esc(r.district||'Distrito pendiente')} · ${esc(r.address||'')}</span><span class="statusPill ${esc(norm(r.lifecycle_status||'NUEVA'))}">${esc(norm(r.lifecycle_status||'NUEVA'))}</span></div></article>`).join('')||'<div class="emptyOps">Sin evidencias para estos filtros.</div>';for(const img of host.querySelectorAll('[data-thumb]'))if(img.dataset.thumb)img.src=await mediaUrl(img.dataset.thumb)}
function updateSelection(){const n=selected.size;$('bulkCount')&&($('bulkCount').textContent=`${n} seleccionadas`);$('reviewSource')&&($('reviewSource').textContent=`${n} seleccionadas`);const codes=selectionCodes();$('missionSource')&&($('missionSource').textContent=codes.length?`${codes.length} evidencias listas para misión`:'Sin selección');$('caseSource')&&($('caseSource').textContent=codes.length?`${codes.length} evidencias listas para caso`:'Sin selección')}
function selectionCodes(){if(selected.size)return[...selected];const map=[...document.querySelectorAll('.nm-marker.selected[data-code]')].map(x=>x.dataset.code);return[...new Set(map)]}
async function openEditor(code){current=rows.find(r=>r.code===code)||null;if(!current)return;renderReview();const h=$('editorOps'),img=current.photo_path?await mediaUrl(current.photo_path):'';h.innerHTML=`<div class="evidenceEditor"><div class="editorPhoto">${img?`<img id="opsPhoto" src="${esc(img)}">`:'<div style="color:#9fb0c7">Sin fotografía</div>'}</div><div class="photoTools"><button class="opsBtn secondary" data-rot="-90">↶ Izquierda</button><button class="opsBtn secondary" data-rot="90">↷ Derecha</button><button class="opsBtn secondary" data-rot="180">↻ 180°</button><button class="opsBtn secondary" data-rot="reset">Restaurar original</button></div><label>Tipo<input id="opType" value="${esc(current.type||'')}"></label><label>Partido<input id="opParty" value="${esc(current.party||'')}"></label><label>Candidato<input id="opCandidate" value="${esc(current.candidate||'')}"></label><label>Cargo<input id="opOffice" value="${esc(current.office||'')}"></label><label>Empresa / proveedor<input id="opProvider" value="${esc(current.provider||'')}"></label><label>Distrito<input id="opDistrict" value="${esc(current.district||'')}"></label><label>Estado territorial<select id="opLife">${['NUEVA','CONFIRMADA','ACTUALIZADA','RETIRADA','NO_ENCONTRADA','PENDIENTE'].map(x=>`<option ${x===norm(current.lifecycle_status||'NUEVA')?'selected':''}>${x}</option>`).join('')}</select></label><label>Revisión<select id="opReview">${['PENDIENTE','REVISADO','ACTUALIZAR','RETIRADO'].map(x=>`<option ${x===norm(current.review_status||'PENDIENTE')?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Observación<textarea id="opNotes">${esc(current.notes||'')}</textarea></label><label class="full">Motivo de corrección<input id="opReason" placeholder="Ej. proveedor confirmado / clasificación corregida"></label><div id="municipalityMatch" class="municipalityMatch">Buscando municipalidad competente…</div><button id="opSave" class="opsBtn full">Guardar y siguiente →</button><div id="auditBox" class="auditBox">Cargando historial…</div></div>`;h.querySelectorAll('[data-rot]').forEach(b=>b.onclick=()=>rotatePhoto(b.dataset.rot));$('opSave').onclick=saveEditor;renderMunicipalityMatch();renderAudit(code)}
async function renderMunicipalityMatch(){if(!current)return;if(!municipalities.length)await loadMunicipalities();const m=matchMunicipality(current),box=$('municipalityMatch');if(!box)return;box.innerHTML=m?`🏛️ <b>${esc(m.municipality_name)}</b><br>${m.authority_name?`${esc(m.authority_title||'ALCALDE')}: ${esc(m.authority_name)}`:'⚠ Autoridad pendiente de fuente oficial'}${m.authority_source_url?`<br>Fuente: ${esc(m.authority_source_url)}`:''}`:`🏛️ Municipio sugerido: <b>Municipalidad ${current.province&&lower(current.province)===lower(current.district)?'Provincial':'Distrital'} de ${esc(current.district||'Distrito pendiente')}</b><br>⚠ Falta registrar autoridad y fuente oficial en Casos / Cartas.`}
function matchMunicipality(r){return municipalities.find(m=>lower(m.district)===lower(r.district)&&( !m.province||!r.province||lower(m.province)===lower(r.province)))||null}
async function renderAudit(code){const r=await api(`control_audit_log?select=action,actor,changes,created_at&entity_type=eq.EVIDENCE&entity_id=eq.${encodeURIComponent(code)}&order=created_at.desc&limit=20`);const a=r.ok?await r.json():[];$('auditBox')&&($('auditBox').innerHTML=a.length?a.map(x=>`<div><b>${esc(x.action)}</b> · ${esc(x.actor||'')} · ${esc(fmtDate(x.created_at))}<br>${esc(JSON.stringify(x.changes||{}))}</div>`).join('<hr>'):'Sin cambios registrados todavía.')}
async function saveEditor(){if(!current)return;const next={type:norm($('opType').value),party:norm($('opParty').value),candidate:norm($('opCandidate').value),office:norm($('opOffice').value),provider:norm($('opProvider').value),district:norm($('opDistrict').value),lifecycle_status:norm($('opLife').value),review_status:norm($('opReview').value),notes:norm($('opNotes').value),edit_reason:norm($('opReason').value),updated_at:new Date().toISOString()};const changes={};for(const [k,v] of Object.entries(next))if(k!=='updated_at'&&String(current[k]??'')!==String(v??''))changes[k]={from:current[k]??'',to:v};if(!Object.keys(changes).length)return;const r=await api(`control_evidences?id=eq.${current.id}`,{method:'PATCH',body:JSON.stringify(next),headers:{Prefer:'return=minimal'}});if(!r.ok)return alert('No se pudo guardar');await audit('EVIDENCE',current.code,'EDIT',changes);Object.assign(current,next);const list=reviewFiltered(),i=list.findIndex(x=>x.code===current.code),n=list[i+1];if(n)openEditor(n.code);else{renderReview();renderAudit(current.code)}}
async function rotatePhoto(deg){if(!current?.photo_path)return alert('Esta evidencia no tiene foto');if(deg==='reset'){if(!current.photo_original_path)return alert('No existe una versión original separada');const history=[...(current.correction_history||[]),{at:new Date().toISOString(),actor:operator(),action:'RESTORE_ORIGINAL'}],r=await api(`control_evidences?id=eq.${current.id}`,{method:'PATCH',body:JSON.stringify({photo_path:current.photo_original_path,corrected_photo_path:null,correction_history:history,updated_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});if(r.ok){await audit('EVIDENCE',current.code,'PHOTO_RESTORE',{});current.photo_path=current.photo_original_path;current.corrected_photo_path=null;current.correction_history=history;openEditor(current.code)}return}const url=await mediaUrl(current.photo_path),blob=await fetch(url).then(r=>r.blob()),bmp=await createImageBitmap(blob),angle=Number(deg),rad=angle*Math.PI/180,swap=Math.abs(angle)%180===90,canvas=document.createElement('canvas');canvas.width=swap?bmp.height:bmp.width;canvas.height=swap?bmp.width:bmp.height;const c=canvas.getContext('2d');c.translate(canvas.width/2,canvas.height/2);c.rotate(rad);c.drawImage(bmp,-bmp.width/2,-bmp.height/2);const out=await new Promise(res=>canvas.toBlob(res,'image/jpeg',.9));const path=`correcciones/${current.code}-${Date.now()}.jpg`;await uploadBlob(path,out);const history=[...(current.correction_history||[]),{at:new Date().toISOString(),actor:operator(),action:'ROTATE',degrees:angle,from:current.photo_path,to:path}],payload={photo_original_path:current.photo_original_path||current.photo_path,photo_path:path,corrected_photo_path:path,correction_history:history,updated_at:new Date().toISOString()};const r=await api(`control_evidences?id=eq.${current.id}`,{method:'PATCH',body:JSON.stringify(payload),headers:{Prefer:'return=minimal'}});if(r.ok){await audit('EVIDENCE',current.code,'PHOTO_ROTATE',{degrees:angle});Object.assign(current,payload);openEditor(current.code)}}
async function bulkApply(){const ids=rows.filter(r=>selected.has(r.code)).map(r=>r.id),field=$('bulkField').value,value=norm($('bulkValue').value);if(!ids.length||!value)return alert('Selecciona evidencias y escribe el nuevo valor');if(!confirm(`Aplicar ${field} = ${value} a ${ids.length} evidencias?`))return;for(let i=0;i<ids.length;i+=50){const part=ids.slice(i,i+50),r=await api(`control_evidences?id=in.(${part.join(',')})`,{method:'PATCH',body:JSON.stringify({[field]:value,updated_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});if(!r.ok)return alert('Error en edición masiva')}await api('control_audit_log',{method:'POST',body:JSON.stringify(rows.filter(r=>selected.has(r.code)).map(r=>({entity_type:'EVIDENCE',entity_id:r.code,action:'BULK_EDIT',actor:operator(),changes:{[field]:value}}))),headers:{Prefer:'return=minimal'}}).catch(()=>{});await loadReview()}
function renderTerritory(){const by=new Map();for(const r of rows){const k=norm(r.district)||'SIN DISTRITO',x=by.get(k)||{n:0,done:0};x.n++;if(['CONFIRMADA','ACTUALIZADA','RETIRADA','NO_ENCONTRADA'].includes(norm(r.lifecycle_status)))x.done++;by.set(k,x)}const top=[...by.entries()].sort((a,b)=>b[1].n-a[1].n).slice(0,12),host=$('territoryGrid');if(!host)return;host.innerHTML=top.map(([d,x])=>{const p=x.n?Math.round(x.done/x.n*100):0;return`<div class="territoryCard" data-district="${esc(d)}"><b>${esc(d)}</b><span>${x.n} evidencias · ${p}% revisado</span><div class="territoryBar"><i style="width:${p}%"></i></div></div>`}).join('');host.onclick=e=>{const c=e.target.closest('[data-district]');if(!c)return;const f=$('fDistrict');if(f){f.value=c.dataset.district;f.dispatchEvent(new Event('change'))}setTab('map')}}
async function loadMissions(){await fetchRows();const r=await api('control_missions?select=*&order=created_at.desc&limit=500');missions=r.ok?await r.json():[];renderMissions();updateSelection()}
function renderMissions(){const stats={PREPARADA:0,ASIGNADA:0,EN_CAMPO:0,CERRADA:0};missions.forEach(m=>stats[m.status]=(stats[m.status]||0)+1);$('missionStats').innerHTML=Object.entries(stats).map(([k,v])=>`<div><b>${v}</b><span>${k.replace('_',' ')}</span></div>`).join('');$('missionList').innerHTML=missions.map(m=>`<article class="missionRow"><b>${esc(m.code)} · ${esc(m.name)}</b><small>${esc(m.assigned_to||'Sin responsable')} · ${esc(m.status)} · ${m.expected_count||0} evidencias</small><small>${esc(m.district||'Zona por selección')} · vence ${esc(m.due_date||'sin fecha')}</small><div class="rowActions"><button data-mission-advance="${m.id}">Avanzar estado</button><button data-mission-xlsx="${m.id}">Exportar Excel</button></div></article>`).join('')||'<div class="emptyOps">Aún no hay misiones.</div>'}
function missionSelection(){return selectionCodes()}
async function createMission(){const codes=missionSelection();if(!codes.length)return alert('Selecciona evidencias en Revisión o dibuja un perímetro en Mapa');const ev=rows.filter(r=>codes.includes(r.code)),district=[...new Set(ev.map(x=>x.district).filter(Boolean))];const code=`MIS-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-5)}`,payload={code,name:norm($('missionName').value)||code,assigned_to:norm($('missionAssignee').value),objective:norm($('missionObjective').value),district:district.length===1?district[0]:null,status:'PREPARADA',evidence_codes:codes,expected_count:codes.length,due_date:$('missionDue').value||null,updated_at:new Date().toISOString()};const r=await api('control_missions',{method:'POST',body:JSON.stringify(payload),headers:{Prefer:'return=representation'}});if(!r.ok)return alert('No se pudo crear la misión');await audit('MISSION',code,'CREATE',{count:codes.length,assigned_to:payload.assigned_to});await loadMissions()}
async function advanceMission(id){const m=missions.find(x=>x.id===id);if(!m)return;const seq=['PREPARADA','ASIGNADA','EN_CAMPO','RECIBIDA','AUDITADA','CERRADA'],next=seq[Math.min(seq.length-1,seq.indexOf(m.status)+1)];await api(`control_missions?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:next,updated_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});await audit('MISSION',m.code,'STATUS',{from:m.status,to:next});loadMissions()}
async function loadXLSX(){if(window.XLSX)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function exportMission(id){const m=missions.find(x=>x.id===id);if(!m)return;await loadXLSX();const ev=rows.filter(r=>(m.evidence_codes||[]).includes(r.code)),data=ev.map(r=>({'CÓDIGO':r.code,'FECHA':r.capture_date,'HORA':r.capture_time,'LATITUD':r.latitude,'LONGITUD':r.longitude,'DISTRITO':r.district,'DIRECCIÓN':r.address,'TIPO':r.type,'PARTIDO':r.party,'EMPRESA / PROVEEDOR':r.provider,'ESTADO MISIÓN':'REVISAR / ACTUALIZAR','OBSERVACIÓN CAMPO':''})),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'DATOS_TECNICOS');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['CÓDIGO MISIÓN',m.code],['NOMBRE',m.name],['RESPONSABLE',m.assigned_to],['OBJETIVO',m.objective],['ESTADO',m.status],['EVIDENCIAS',ev.length]]),'MISION_CONFIG');XLSX.writeFile(wb,`${m.code}.xlsx`)}
async function loadMunicipalities(){const r=await api('control_municipalities?select=*&order=district.asc&limit=1000');municipalities=r.ok?await r.json():[];return municipalities}
async function loadCases(){await Promise.all([fetchRows(),loadMunicipalities()]);const r=await api('control_cases?select=*&order=created_at.desc&limit=500');cases=r.ok?await r.json():[];renderCases();updateSelection()}
function renderCases(){$('authorityList').innerHTML=municipalities.slice(0,100).map(m=>`<article class="authorityRow"><b>${esc(m.municipality_name)}</b><small>${esc(m.district)} · ${esc(m.authority_title||'ALCALDE')}: ${esc(m.authority_name||'PENDIENTE')}</small><small>${m.authority_source_url?'Fuente registrada':'⚠ Sin fuente oficial'}</small></article>`).join('')||'<div class="emptyOps">No hay autoridades cargadas todavía.</div>';$('caseList').innerHTML=cases.map(c=>`<article class="caseRow ${currentCase?.id===c.id?'on':''}" data-case="${c.id}"><b>${esc(c.code)} · ${esc(c.district||'Sin distrito')}</b><small>${esc(c.subject||'Sin asunto')} · ${esc(c.status)} · ${(c.evidence_codes||[]).length} evidencias</small><div class="rowActions"><button data-case-open="${c.id}">Abrir</button></div></article>`).join('')||'<div class="emptyOps">Aún no hay casos.</div>'}
async function saveAuthority(){const payload={region:norm($('authRegion').value),province:norm($('authProvince').value),district:norm($('authDistrict').value),municipality_name:norm($('authMunicipality').value),authority_name:norm($('authName').value)||null,authority_title:norm($('authTitle').value)||'ALCALDE',authority_source_url:norm($('authSource').value)||null,updated_at:new Date().toISOString()};if(!payload.district||!payload.municipality_name)return alert('Distrito y Municipalidad son obligatorios');const r=await api('control_municipalities?on_conflict=region,province,district',{method:'POST',body:JSON.stringify(payload),headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});if(!r.ok)return alert('No se pudo guardar el catálogo');await audit('MUNICIPALITY',payload.district,'UPSERT',{municipality:payload.municipality_name,authority:payload.authority_name,source:payload.authority_source_url});loadCases()}
async function createCase(){const codes=selectionCodes();if(!codes.length)return alert('Selecciona evidencias primero');const ev=rows.filter(r=>codes.includes(r.code)),district=norm($('caseDistrict').value)||([...new Set(ev.map(x=>x.district).filter(Boolean))].length===1?ev[0].district:'');if(!district)return alert('Indica el distrito');const m=municipalities.find(x=>lower(x.district)===lower(district)),code=`CAS-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-5)}`,subject=norm($('caseSubject').value)||`Comunicación sobre evidencias de propaganda electoral en ${district}`,authority=m?.authority_name||'[AUTORIDAD PENDIENTE DE VALIDAR]',mun=m?.municipality_name||`Municipalidad Distrital de ${district}`,letter=`Señor(a)\n${authority}\n${m?.authority_title||'ALCALDE'}\n${mun}\n\nAsunto: ${subject}\n\nDe nuestra consideración:\n\nPor medio de la presente se comunica la existencia de ${codes.length} evidencia(s) de propaganda electoral registrada(s) en la jurisdicción de ${district}. Las evidencias adjuntas contienen fecha, ubicación georreferenciada, código de verificación y registro fotográfico para su revisión correspondiente.\n\nSe adjunta la relación de evidencias para las acciones que correspondan.\n\nAtentamente,\nONE SHOT CONTROL`;const payload={code,district,municipality_id:m?.id||null,subject,status:'BORRADOR',evidence_codes:codes,letter_body:letter,updated_at:new Date().toISOString()};const r=await api('control_cases',{method:'POST',body:JSON.stringify(payload),headers:{Prefer:'return=representation'}});if(!r.ok)return alert('No se pudo crear el caso');await audit('CASE',code,'CREATE',{district,count:codes.length,municipality:m?.municipality_name||null});await loadCases();openCase((await r.json())[0]?.id)}
async function openCase(id){currentCase=cases.find(c=>c.id===id)||null;if(!currentCase)return;const m=municipalities.find(x=>x.id===currentCase.municipality_id),ev=rows.filter(r=>(currentCase.evidence_codes||[]).includes(r.code));$('letterPreview').textContent=(currentCase.letter_body||'')+`\n\nANEXO DE EVIDENCIAS\n`+ev.map((r,i)=>`${i+1}. ${r.code} · ${r.type||'PENDIENTE'} · ${r.party||'Partido pendiente'} · ${r.address||''}`).join('\n');renderCases()}
function printLetter(){if(!currentCase)return alert('Selecciona un caso');const m=municipalities.find(x=>x.id===currentCase.municipality_id),ev=rows.filter(r=>(currentCase.evidence_codes||[]).includes(r.code)),w=window.open('','_blank');w.document.write(`<html><head><title>${esc(currentCase.code)}</title><style>body{font-family:Arial;margin:40px;line-height:1.5}h1{font-size:20px}.ev{page-break-inside:avoid;border-top:1px solid #ddd;padding:12px 0}.ev img{max-width:320px;max-height:220px;object-fit:contain}</style></head><body><h1>${esc(currentCase.code)}</h1><pre style="white-space:pre-wrap;font-family:Arial">${esc(currentCase.letter_body||'')}</pre><h2>Anexo de evidencias</h2>${ev.map((r,i)=>`<div class="ev"><b>${i+1}. ${esc(r.code)} · ${esc(r.type||'')}</b><br>${esc(r.address||'')}<br>${esc(r.party||'')}</div>`).join('')}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
async function advanceCase(){if(!currentCase)return;const seq=['BORRADOR','LISTO_PARA_ENVIO','ENVIADO','RESPONDIDO','CERRADO'],next=seq[Math.min(seq.length-1,seq.indexOf(currentCase.status)+1)];await api(`control_cases?id=eq.${currentCase.id}`,{method:'PATCH',body:JSON.stringify({status:next,updated_at:new Date().toISOString(),sent_at:next==='ENVIADO'?new Date().toISOString():currentCase.sent_at}),headers:{Prefer:'return=minimal'}});await audit('CASE',currentCase.code,'STATUS',{from:currentCase.status,to:next});currentCase.status=next;loadCases()}
function bindModules(){$('rvSearch').oninput=renderReview;$('rvDistrict').onchange=renderReview;$('rvType').onchange=renderReview;$('rvLife').onchange=renderReview;$('reviewList').onclick=e=>{const ck=e.target.closest('[data-check]');if(ck){e.stopPropagation();ck.checked?selected.add(ck.dataset.check):selected.delete(ck.dataset.check);updateSelection();return}const a=e.target.closest('[data-rv]');if(a)openEditor(a.dataset.rv)};$('bulkApply').onclick=bulkApply;$('missionCreate').onclick=createMission;$('missionReload').onclick=loadMissions;$('missionList').onclick=e=>{const a=e.target.closest('[data-mission-advance]'),x=e.target.closest('[data-mission-xlsx]');if(a)advanceMission(a.dataset.missionAdvance);if(x)exportMission(x.dataset.missionXlsx)};$('authSave').onclick=saveAuthority;$('caseCreate').onclick=createCase;$('casesReload').onclick=loadCases;$('caseList').onclick=e=>{const b=e.target.closest('[data-case-open]');if(b)openCase(b.dataset.caseOpen)};$('letterPrint').onclick=printLetter;$('caseAdvance').onclick=advanceCase}
async function boot(){injectShell();await Promise.all([fetchRows(),loadMunicipalities()]);renderTerritory();console.info('[ONE SHOT CONTROL]',BUILD)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,200),{once:true});else setTimeout(boot,200);
})();
