'use strict';
(()=>{
const BUCKET='one-shot-evidence';let CFG=null;
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const encPath=p=>String(p||'').split('/').map(encodeURIComponent).join('/');
const safe=s=>String(s||'').replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,100)||'evidencia';
async function config(){if(CFG)return CFG;const src=[...document.scripts].map(s=>s.src).find(s=>/\/control\/app\.js/.test(s))||'app.js';const text=await fetch(src,{cache:'no-store'}).then(r=>r.text()),u=(text.match(/SUPA_URL='([^']+)'/)||[])[1],k=(text.match(/SUPA_KEY='([^']+)'/)||[])[1];if(!u||!k)throw new Error('No se encontró la configuración central');return CFG={url:u,key:k}}
async function api(path,opts={}){const c=await config();return fetch(`${c.url}/rest/v1/${path}`,{...opts,headers:{apikey:c.key,Authorization:'Bearer '+c.key,'Content-Type':'application/json',...(opts.headers||{})}})}
async function publicMedia(p){const c=await config();return p?`${c.url}/storage/v1/object/public/${BUCKET}/${encPath(p)}`:''}
function progress(show,title='',detail='',pct=0){const box=$('importProgress');if(!box)return;box.hidden=!show;$('importProgressTitle').textContent=title;$('importProgressDetail').textContent=detail;$('importProgressBar').style.width=Math.max(0,Math.min(100,pct))+'%'}
function summary(text,tone='ok'){const el=$('importSummary');if(!el)return;el.hidden=!text;el.dataset.tone=tone;el.textContent=text}
async function workerRead(file){const buf=await file.arrayBuffer();return new Promise((resolve,reject)=>{const w=new Worker('xlsx-media-worker-v600.js?v=600'),timer=setTimeout(()=>{w.terminate();reject(new Error('La lectura del Excel excedió el tiempo esperado'))},120000);w.onmessage=e=>{const d=e.data||{};if(d.type==='progress'){const pct=d.stage==='excel'?8:d.stage==='rows'?25:d.stage==='photos'?25+Math.round((d.done||0)/Math.max(1,d.total||1)*35):10;progress(true,'Procesando Excel',d.message||`${d.done||0} / ${d.total||0}`,pct)}else if(d.type==='done'){clearTimeout(timer);w.terminate();resolve(d)}else if(d.type==='error'){clearTimeout(timer);w.terminate();reject(new Error(d.message||'No se pudo procesar el Excel'))}};w.onerror=err=>{clearTimeout(timer);w.terminate();reject(new Error(err.message||'Error del lector de Excel'))};w.postMessage({buffer:buf,name:file.name},[buf])})}
async function existingCodes(codes){const found=new Set();for(let i=0;i<codes.length;i+=60){const part=codes.slice(i,i+60).map(x=>'"'+String(x).replace(/"/g,'')+'"').join(','),r=await api(`control_evidences?select=code&code=in.(${encodeURIComponent(part)})`);if(r.ok)for(const x of await r.json())found.add(x.code);await sleep(0)}return found}
async function uploadPhoto(code,m){const c=await config(),ext=m.ext==='png'?'png':m.ext==='webp'?'webp':'jpg',path=`evidencias/${safe(code)}.${ext}`,url=`${c.url}/storage/v1/object/${BUCKET}/${encPath(path)}`,r=await fetch(url,{method:'POST',headers:{apikey:c.key,Authorization:'Bearer '+c.key,'Content-Type':m.mime||'image/jpeg','x-upsert':'true'},body:m.buffer});if(!r.ok)throw new Error(`Foto ${code}: HTTP ${r.status}`);return path}
async function uploadMedia(rows,media){let done=0,failed=0,cursor=0;async function runner(){while(cursor<media.length){const m=media[cursor++],row=rows[m.dataIndex];if(!row?.code)continue;try{row.photo_path=await uploadPhoto(row.code,m);row.photo_mime=m.mime;row.photo_bytes=m.buffer.byteLength;row.media_updated_at=new Date().toISOString()}catch(e){failed++;console.warn(e)}done++;progress(true,'Subiendo fotografías',`${done} de ${media.length} · ${failed} con error`,60+Math.round(done/Math.max(1,media.length)*20));await sleep(0)}}await Promise.all([runner(),runner()]);return{done:done-failed,failed}}
async function upsertRows(rows){for(let i=0;i<rows.length;i+=100){const part=rows.slice(i,i+100).map(r=>({...r,updated_at:new Date().toISOString()})),res=await api('control_evidences?on_conflict=code',{method:'POST',body:JSON.stringify(part),headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});if(!res.ok)throw new Error(`No se pudo consolidar la data (HTTP ${res.status})`);progress(true,'Consolidando evidencias',`${Math.min(i+100,rows.length)} de ${rows.length}`,82+Math.round(Math.min(i+100,rows.length)/Math.max(1,rows.length)*15));await sleep(0)}}
async function importExcel(file){const input=$('excelEvidenceInput');if(input)input.disabled=true;summary('');progress(true,'Preparando importación',file.name,3);try{const result=await workerRead(file),rows=result.rows||[],media=result.media||[];if(!rows.length)throw new Error('El archivo no contiene evidencias con coordenadas válidas');const existing=await existingCodes(rows.map(r=>r.code));progress(true,'Excel reconocido',`${rows.length} evidencias · ${media.length} fotos incrustadas`,58);const photos=await uploadMedia(rows,media);await upsertRows(rows);await api('control_imports',{method:'POST',body:JSON.stringify({file_name:file.name,row_count:rows.length}),headers:{Prefer:'return=minimal'}}).catch(()=>{});progress(true,'Actualizando mapa','Cargando base central…',99);$('reloadBtn')?.click();await sleep(700);await refreshMediaKpi();progress(false);summary(`✓ ${rows.length} evidencias · ${rows.length-existing.size} nuevas · ${existing.size} actualizadas · ${photos.done} fotos publicadas${photos.failed?` · ${photos.failed} fotos con error`:''}`,'ok')}catch(e){console.error(e);progress(false);summary(`⚠ ${e.message||e}`,'error')}finally{if(input){input.disabled=false;input.value=''}}}
async function getEvidence(code){const r=await api(`control_evidences?select=code,type,party,district,address,latitude,longitude,capture_date,capture_time,gps_accuracy,review_status,photo_path,notes&code=eq.${encodeURIComponent(code)}&limit=1`);if(!r.ok)return null;return(await r.json())[0]||null}
async function showPreview(code){if(!code||!$('evidencePreview'))return;$('evidencePreview').hidden=false;$('previewCode').textContent=code;$('previewMeta').textContent='Cargando evidencia…';const r=await getEvidence(code);if(!r){$('previewMeta').textContent='No se pudo cargar la ficha';return}const img=$('previewImg'),empty=$('previewEmpty');if(r.photo_path){img.src=await publicMedia(r.photo_path);img.hidden=false;empty.hidden=true}else{img.removeAttribute('src');img.hidden=true;empty.hidden=false}$('previewMeta').textContent=[r.type||'PENDIENTE',r.party||'Partido pendiente',r.district||'Distrito pendiente',r.capture_date||'',r.capture_time||'',Number.isFinite(+r.gps_accuracy)?`GPS ±${r.gps_accuracy}m`:null].filter(Boolean).join(' · ');$('previewAddress').textContent=r.address||'Dirección pendiente';const maps=$('previewMaps');maps.href=`https://www.google.com/maps?q=${encodeURIComponent(`${r.latitude},${r.longitude}`)}`;maps.hidden=!(Number.isFinite(+r.latitude)&&Number.isFinite(+r.longitude));const open=$('previewOpen');open.href=r.photo_path?await publicMedia(r.photo_path):'#';open.hidden=!r.photo_path}
async function refreshMediaKpi(){try{const r=await api('control_evidences?select=code&photo_path=not.is.null&limit=10000');if(r.ok)$('kWithPhoto').textContent=(await r.json()).length}catch(_){} }
function bindPreview(){const codeEl=$('eCode');if(codeEl)new MutationObserver(()=>showPreview(codeEl.textContent.trim())).observe(codeEl,{childList:true,characterData:true,subtree:true});$('rows')?.addEventListener('click',e=>{const row=e.target.closest('[data-code]');if(row)setTimeout(()=>showPreview(row.dataset.code),0)},true)}
function boot(){const input=$('excelEvidenceInput');input?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importExcel(f)});bindPreview();setTimeout(refreshMediaKpi,900);console.info('[ONE SHOT CONTROL] dashboard-v600')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
